### ISSUE TITLE
shared storage host/guest

### ISSUE THREAD

**Issue by kugelzucker** [pr1ntf/iohyve#107]
(doubled via twitter, sorry. but its more transparent here.)

first of: thanks! iohyve is the ezjails vm-equivalent that i have been looking for.

a feature request, and please squash if its not the right place or time.

i am new to VM so i am not sure if its possible but i would love some shared storage between host and guest similar to nullfs with freebsd-jails. in this case its both a freebsd host and guest and i'd like to read data as the host from the guest to process after it finished downloading on the guest.

i know this can be done via NFS or sshfs (fuse), or rsync, but those are all taking the long route over the network and that seems silly to me.

i am aware that VM brings the added challenge of the guest system being somewhat more autonomous in its functions and that unlike jails its not using the same zfs-daemon anyways, hence nullfs is a nobrainer.
still, i would like to raise the question if something like this is possible. maybe through reading the ZVOL i have created on the host (which i cant find for the life of me, btw ...)? 

EDIT: found it. /dev/zvol/$pool/iohve/$guest (which was kinda obvious)

just a thought, maybe its possible. it would be  a GREAT addition to bhyve & iohyve.

**Comment by pr1ntf** [comment]
> first of: thanks! iohyve is the ezjails vm-equivalent that i have been looking for.

Thanks for the kind words!

> i am new to VM so i am not sure if its possible but i would love some shared storage between host and guest similar to nullfs with freebsd-jails

Although the `nullfs` idea seems like a great idea, I don't think I'll throw the effort at "making it stick" right now with all the changes to networking. I'm going to close this issue for now, but will likely come back to it at a later date. 

If I were to start hacking away, I would start with trying to get a `nullfs` device mounted in just a regular "hand launched" `bhyve` instance. If you do end up hacking on this yourself, feel free to pop in here or even the `freebsd-virtualization` mailing list with info. :smile:
