### ISSUE TITLE
Doesn't work on secondary datasets

### ISSUE THREAD

**Issue by corv89** [pr1ntf/iohyve#110]
The system is running on 'tank'.

Setting up iohyve on 'other':
`sudo iohyve setup pool=other`
`Setting up iohyve pool...`

Attempting to set debguest:
`sudo iohyve set debguest loader=grub-bhyve`
`Setting debguest prop loader=grub-bhyve...`
`cannot open '/iohyve/debguest': invalid dataset name`

other/iohyve exists:
`zfs list -r other`
`other/iohyve`
`other/iohyve/Firmware`
`other/iohyve/ISO`

**Comment by nlienard** [comment]
at first, you need to create the guest :

# sudo iohyve create [name] [size]

ex:

# sudo iohyve create debguest 10G

**Comment by corv89** [comment]
my bad!
