### ISSUE TITLE
Can't delete guest from automated script

### ISSUE THREAD

**Issue by kmoore134** [pr1ntf/iohyve#113]
In the __delete() function, this line:

read -p "Are you sure you want to delete $name and all associated datasets [Y/N]? " an </dev/tty

We need a way to skip the /dev/tty and read line. (Maybe -F?) This is for our new API, which of course doesn't have an active /dev/tty to read from.

**Comment by kmoore134** [comment]
Ditto for the __rmpci() and __remove() functions as well.

**Comment by pr1ntf** [comment]
Great idea!
I've also found three instances:
https://github.com/pr1ntf/iohyve/blob/master/iohyve#L824
https://github.com/pr1ntf/iohyve/blob/master/iohyve#L892
https://github.com/pr1ntf/iohyve/blob/master/iohyve#L953

Adding a check for another flag will require a rewrite of those functions, but shouldn't take long™.

**Comment by pr1ntf** [comment]
This has been implemented. Adding `-f` before the name of the guest will not prompt for deletion. 

Nice API by the way!
