### ISSUE TITLE
Cannot create debian guest

### ISSUE THREAD

**Issue by allenmchan** [pr1ntf/iohyve#114]
I am testing this on Freenas 9.10 which is based on FreeBSD 10.3-RC3.
Running into problems with provided steps.

[root@freenas] ~# iohyve version
iohyve v0.7 2015/10/27 Im Here for the Party Edition

[root@freenas] ~# zfs list | grep -i iohyve
DATASTORE/iohyve                                            20.6G  5.43T   208K  /mnt/iohyve
DATASTORE/iohyve/Firmware                                    192K  5.43T   192K  /mnt/iohyve/Firmware
DATASTORE/iohyve/ISO                                         384K  5.43T   192K  /mnt/iohyve/ISO
DATASTORE/iohyve/ISO/ubuntu-14.04.4-server-amd64.iso         192K  5.43T   192K  /mnt/iohyve/ISO/ubuntu-14.04.4-server-amd64.iso
DATASTORE/iohyve/ubuntuguest                                20.6G  5.43T   192K  /mnt/iohyve/ubuntuguest
DATASTORE/iohyve/ubuntuguest/disk0                          20.6G  5.45T   128K  -

[root@freenas] ~# iohyve create ubuntuguest 20G
Creating ubuntuguest...

[root@freenas] ~# iohyve set ubuntuguest loader=grub-bhyve
Setting ubuntuguest prop loader=grub-bhyve...

[root@freenas] ~# iohyve set ubuntuguest os=debian
Setting ubuntuguest prop os=debian...

[root@freenas] ~# iohyve set ubuntuguest ram=1024M
Setting ubuntuguest prop ram=1024M...

[root@freenas] ~# iohyve set ubuntuguest cpu=2
Setting ubuntuguest prop cpu=2...

[root@freenas] ~# iohyve set ubuntuguest con=nmdm1
Setting ubuntuguest prop con=nmdm1...

[root@freenas] ~# iohyve isolist
Listing ISO's...
ubuntu-14.04.4-server-amd64.iso

[root@freenas] ~# iohyve install ubuntuguest ubuntu-14.04.4-server-amd64.iso
Not a valid guest name

[root@freenas] ~# iohyve list
Guest        VMM?  Running?  rcboot?  Description
ubuntuguest  NO    NO        NO       Fri_Mar_25_12:46:32_PDT_2016

[root@freenas] ~# iohyve console ubuntuguest
Starting console on ubuntuguest...
~~. to escape console [uses cu(1) for console]
/dev/nmdm1B: No such file or directory
link down

**Comment by allenmchan** [comment]
From what i could tell, it looks like iohyve is expecting everything in /iohyve but it is /mnt/iohyve by default.

After adding symbolic link, i get this error now
[root@freenas] ~# iohyve install ubuntuguest ubuntu-14.04.4-server-amd64.iso
Installing ubuntuguest...
Could not create VM ioh-ubuntuguest
Error in initializing VM
[root@freenas] ~# vm_create: No such file or directory

**Comment by pr1ntf** [comment]
I'm sorry, I don't have access to running FreeNAS + bhyve on anything at the moment, so you'll have to bear with me for the time being until I can figure something out about those mount points. 

For the time being, there are a few things I'd like to point out:
- You're using an outdated version of `iohyve`, you can either use a fresh version from GitHub, or use the one in ports, which should be version `0.7.3` still under the release name of `Bear in a Datacenter Edition`
- Unless you are wanting a specific `nmdm` port, there is no need to set the `con` property, as `iohyve` will set this automatically for you.

**Comment by allenmchan** [comment]
Thanks for responding. I have asked the freenas dev team to load latest version and they will in the next update. I have a workaround that got this working but it would be nice if you patch the code to detect this situation. Maybe either give the user an ability to specify the dir or find it yourself?

**Comment by pr1ntf** [comment]
Strange why they didn't put in the latest version that's in ports.

If possible, could you give the commands you used to fix this? It would help in the meantime until I can find a solution. Doesn't have to be in depth, just something we can put on the `README.md` page.

**Comment by pr1ntf** [comment]
I did some digging in the documents and found this page detailing the link:
http://doc.freenas.org/9.10/freenas_jails.html#using-iohyve

`ln -s /mnt/iohyve /iohyve`

Closing issue out. 

I'm adding the ability to let the `iohyve` datasets live wherever they want on the [list](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#079-goals).

Thanks for your help!

**Comment by jonblack** [comment]
@allenmchan What was your workaround? I have the same issue, and the symbolic link already exists.

**Comment by pr1ntf** [comment]
Feel free to add some output so we can take a look. I'd love to help, too.

**Comment by jonblack** [comment]
Here's some output from the limited commands I know. If you need more, let me know and I'll edit this comment.

```
[root@mnemosyne] ~# iohyve list
Guest      VMM?  Running  rcboot?  Description
debian8.3  NO    NO       NO       Sun Apr 24 14:01:51 CEST 2016

[root@mnemosyne] ~# iohyve start debian8.3
Starting debian8.3... (Takes 15 seconds for FreeBSD guests)
[root@mnemosyne] ~# Could not create VM ioh-debian8.3
Error in initializing VM
vm_create: No such file or directory
VM:ioh-debian8.3 is not created.

[root@mnemosyne] ~# ls -l /io*
lrwxrwxr-x  1 root  wheel  11 Apr 24 13:47 /iohyve@ -> /mnt/iohyve
```

I create the virtual machine yesterday and it worked. Overnight the service shutdown and I turned it on again this morning, and now it's not working.

**Comment by pr1ntf** [comment]
This looks like the output of an error where `vmm.ko` is not loaded. 
At least, this is the error I get when it's not loaded. 

`kldstat` should tell you if it's loaded. If you see `vmm.ko` in the output, and you're still seeing this error, please report back.

**Comment by jonblack** [comment]
Thanks. `vmm.ko` is indeed not loaded:

```
[root@mnemosyne] ~# kldstat 
Id Refs Address            Size     Name
 1   80 0xffffffff80200000 17de000  kernel
 2    1 0xffffffff81cb0000 ffd8c    ispfw.ko
 3    1 0xffffffff81e11000 f947     geom_mirror.ko
 4    1 0xffffffff81e21000 46a1     geom_stripe.ko
 5    1 0xffffffff81e26000 ffca     geom_raid3.ko
 6    1 0xffffffff81e36000 ec6a     geom_raid5.ko
 7    1 0xffffffff81e45000 574f     geom_gate.ko
 8    1 0xffffffff81e4b000 4a32     geom_multipath.ko
 9    1 0xffffffff81e50000 5718     fdescfs.ko
10    1 0xffffffff81e56000 89c      dtraceall.ko
11   10 0xffffffff81e57000 3ad17    dtrace.ko
12    1 0xffffffff81e92000 4638     dtmalloc.ko
13    1 0xffffffff81e97000 225b     dtnfscl.ko
14    1 0xffffffff81e9a000 63d8     fbt.ko
15    1 0xffffffff81ea1000 58109    fasttrap.ko
16    1 0xffffffff81efa000 49cb     lockstat.ko
17    1 0xffffffff81eff000 15f9     sdt.ko
18    1 0xffffffff81f01000 d8d7     systrace.ko
19    1 0xffffffff81f0f000 d493     systrace_freebsd32.ko
20    1 0xffffffff81f1d000 4da4     profile.ko
21    1 0xffffffff81f22000 7fdf     ipmi.ko
22    1 0xffffffff81f2a000 b3b      smbus.ko
23    1 0xffffffff81f2b000 1a63a    hwpmc.ko
24    2 0xffffffff81f46000 2b32     vboxnetflt.ko
25    2 0xffffffff81f49000 45370    vboxdrv.ko
26    1 0xffffffff81f8f000 41cb     ng_ether.ko
27    1 0xffffffff81f94000 3fd4     vboxnetadp.ko
28    1 0xffffffff81f98000 9fc6     linprocfs.ko
29    1 0xffffffff81fa2000 66fb     linux_common.ko
```

When I run `kldload vmm.ko` and then `iohyve start debian8.3` I get the following:

```
[root@mnemosyne] ~# iohyve start debian8.3
Starting debian8.3... (Takes 15 seconds for FreeBSD guests)
[root@mnemosyne] ~# Unable to initialize backend '/dev/nmdm0A' for LPC device COM1
```

And the VM is still down:

```
[root@mnemosyne] ~# iohyve list
Guest      VMM?  Running  rcboot?  Description
debian8.3  NO    NO       NO       Sun Apr 24 14:01:51 CEST 2016
```

So two questions:
1. How do you get `vmm.ko` to load automatically?
2. How do I fix the backend initialization error?

In case you need to know, I'm using `iohyve v0.7.5 2016/04/14 Tennessee Cherry Moonshine Edition`.

**Comment by pr1ntf** [comment]
> How do I fix the backend initialization error?

This is most likely due to the `nmdm` kernel module not being loaded either. 

> How do you get vmm.ko to load automatically?

You can have iohyve load the necessary modules at boot time. Check out the "Pre-flight checklist" in the [readme](https://github.com/pr1ntf/iohyve/blob/master/README.md) or [manpage](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L63) for more information, but in short, you can add the following lines to your `/etc/rc.conf` (note: I left out the `net=[iface]` flag, but you can use it to set up the networking if you choose):

```
iohyve_enable="YES"
iohyve_flags="kmod=1"
```

You can also follow the guidelines in the [FreeBSD Handbook](https://www.freebsd.org/doc/handbook/virtualization-host-bhyve.html) (Section 21.7.7) and add the following lines to your `/boot/loader.conf` file:

```
vmm_load="YES"
nmdm_load="YES"
if_bridge_load="YES"
if_tap_load="YES"
```

I'd also like to point out that running bhyve and VirtualBox modules at the same time has caused kernel panics in the past. You may want to watch out for that.

**Comment by pr1ntf** [comment]
I'm closing this issue again, but feel free to respond if you need further assistance, or open a new issue altogether if you so choose.
