### ISSUE TITLE
Getting all properties breaks with spaces. 

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#115]
Using `zfs get -H all $pool/iohyve/$name` in places breaks the `description` property because it has spaces. 

This is true for the `getall` and `export` functions.

**Comment by EpiJunkie** [comment]
I just [submitted a pull request to address this issue](https://github.com/pr1ntf/iohyve/pull/120) for `iohyve getall`

I am guessing the `export` subfunction is in development. I image if you want to export that value easily you could use this:

`zfs get -H -o value iohyve:description $pool/iohyve/$name`

**Comment by pr1ntf** [comment]
That is indeed the work-around right now for the in-development `export` function.

I will be re-doing my version of that function once PR #120 get's pushed.

**Comment by pr1ntf** [comment]
Closing, #120 is pushed.
