### ISSUE TITLE
ability to specific tapN mac address

### ISSUE THREAD

**Issue by SquallATF** [pr1ntf/iohyve#116]
if not specific tapN mac address, the mac address may changed, and ubuntu will gen new net config in /etc/udev/rules.d/70-persistent-net.rules, and then system can not get ip because of wrong eth name

> ```
>            tapN[,mac=xx:xx:xx:xx:xx:xx]
> 
>            vmnetN[,mac=xx:xx:xx:xx:xx:xx]
> 
>                If mac is not specified, the MAC
>                address is derived from a fixed OUI
>                and the remaining bytes from an MD5
>                hash of the slot and function numbers
>                and the device name.
> ```

**Comment by pr1ntf** [comment]
`iohyve` has the ability to force a specific MAC address to be used for a tap. 

https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L194

For instance, if the tap interface on your Ubuntu guest is `tap5` you can run something like `iohyve set ubuntu-guest mac_tap5=xx:xx:xx:xx:xx:xx`.
