### ISSUE TITLE
Error while starting Ubuntu VM after upgrading to 10.3-RELEASE

### ISSUE THREAD

**Issue by mohshami** [pr1ntf/iohyve#128]
Hey bro,

After upgrading from 10.2-RELEASE to 10.3-RELEASE I get the following error 

Starting servicedesk... (Takes 15 seconds for FreeBSD guests)
root@sauron:~ # Could not setup memory for VM
Error in initializing VM
Unable to setup memory (-1)

I'm running iohyve "v0.7.3 2016/01/08 Bear in a Datacenter Edition" from ports

Thanks a million

**Comment by pr1ntf** [comment]
Can you also include the output of `iohyve getall servicedesk`?

Thanks!

**Comment by mohshami** [comment]
Of course, sorry for the late reply

Getting servicedesk props...
autogrub     \n
os           debian
tap          tap0
con          nmdm1
boot         1
description  Tue
name         servicedesk
bargs        -A_-H_-P
loader       grub-bhyve
persist      1
install      no
size         120G
ram          8G
cpu          2

**Comment by pr1ntf** [comment]
Nothing is standing out to me so far. Can you try a few things like destroying the VM resources first with something like `iohyve destroy servicedesk`(it won't delete data) and then make sure it's gone by running something like `ls /dev/vmm`. 

After that, unload and load the `vmm` kernel module with something like `kldunload vmm` followed by `kldload vmm`.  Make sure it's back by running something like `kldstat` and checking for the `vmm.ko` module listed. 

Once that is complete, try starting the guest again and report back.

**Comment by mohshami** [comment]
Ok now this is really embarrassing.

I have already tried those commands and they didn't work, but as it turns out. This was a "Problem exists between keyboard and chair" kind of problem. I "forgot" to do the second "freebsd-update install" after rebooting the server :laughing: 

I've had moments like this before, but having it public on GitHub is out of this world

Thanks man for the great efforts

**Comment by pr1ntf** [comment]
It happens! 
Thanks for taking the time to open the request at any rate.

**Comment by mohshami** [comment]
It's the least I could do, thanks for the awesome job :)
