### ISSUE TITLE
Is there a way to mount zfs dataset onto bhyve VM?

### ISSUE THREAD

**Issue by allenmchan** [pr1ntf/iohyve#129]
iohyve already does a good job on creating / using a zfs dataset for the disk image. I am wondering if i can use iohyve to mount a separate zfs dataset onto the VM. 

Use case: 
I have a VM that will have a mysql database on it. I want to write the mysql data to a separate zfs dataset so it is not coupled with the VM disk image. If there are any corruption in the VM disk image, the database would be fine. I could then rebuild the VM and just continue to use the database.

In the freenas jails world it is possible but i dont know how that is translated to bhyve VMs
https://doc.freenas.org/9.10/freenas_jails.html#add-storage

**Comment by pr1ntf** [comment]
You can add multiple disks to an iohyve guest. Each disk is stored on a separate zvol.
You can read more on this feature in the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L224).

Hope this helps!
