### ISSUE TITLE
Code suggestions

### ISSUE THREAD

**Issue by churchers** [pr1ntf/iohyve#134]
Here's a list of small bugs or suggestions I've found in the codebase. Some of these are just style things that are probably mainly down to personal preference so feel free to ignore. Bear in mind I haven't tested any of this, it's just from looking through the code. Hopefully this isn't out of place.
##### 1) while loop in `__parse_cmd`

This is the same in iocage and I don't really see why it's there. Every case has an exit statement that ends execution anyway. The while loop would only make sense if you were trying to parse multiple commands passed in the same cmd line, which would be cool, but near impossible to actually implement. As `__parse_cmd` is pretty much the only thing that actually gets run in the main code, you also don't really need to exit after each case, as when `__parse_cmd` returns, the code will exit anyway.

You could also put the `;;` on the same line, reducing each case to 1 line, and cutting the length of the function by almost 2/3rds. Some people have fairly strict style guidelines that `;;` must be on a newline, but I think that's a bit overkill when each case is only 1 line.

```
  version)  __version ;;
  oldset)   __oldset "$@" ;;
```
##### 2) wired memory typos

On line 520, `$wire_memory-m` would probably cause that grub-bhyve command to fail if wired memory was enabled as there's no space between the options. There's also various calls to grub-bhyve that don't have the `$wired_memory` settings, although that could be intentional?
##### 3) UEFI seems to drop back to normal boot

Could probably do with an `exit` after the `__uefi` call, or at the end of the uefi function as it looks to me like it will drop back to the `__start` function, then probably output `Guest is already running`? Also the uefi function seem to check firmware but continues anyway.
##### 4) nested ifs

Another style thing so probably down to preference, I just find lots of nesting makes things harder to read and maintain. You could get rid of quite a bit of nesting by switching if statements the opposite way round, then exiting. For example in `__install` you could do the following:

```
# check valid guest
if [ ! -d /iohyve/$pool/$name -a ! -d /iohyve/$name ]; then
    echo "Not a valid guest name"
    exit 1
fi

# Check to make sure guest isn't running
local running=$(pgrep -fx "bhyve: ioh-$name")
if [ -n $running ]; then
    echo "Guest is already running"
    exit 1
fi

# normal code
```

**Comment by pr1ntf** [comment]
Thank you for your feedback! There's definitely some issues with formatting and a bit of rot in the script. There's been so many hands in `iohyve` it's hard to keep things standard. 

The way things are going it's only going to get worse, so I've been tossing the idea of a feature freeze and audit before we begin work on NETMAP support. (Around `v0.8`) There's also the idea of splitting into libraries and such as well. It may be prudent to do that at the same time. 

I'm closing the issue, but feel free to respond or add any other comments here, they won't fall on deaf ears.
