### ISSUE TITLE
Support reboot in guest

### ISSUE THREAD

**Issue by corny** [pr1ntf/iohyve#136]
If I run `reboot` in a guest, it will be halted. What can I do to keep the guest alive?

Excerpt from /usr/share/examples/bhyve/vmrun.sh:

```
bhyve returns the following status codes:
    0 - VM has been reset
    1 - VM has been powered off
    2 - VM has been halted
    3 - VM generated a triple fault
    all other non-zero status codes are errors
```

**Comment by EpiJunkie** [comment]
Which OS do you observe this behaviour? What OS is the host?

I have too experienced similar results. 

If `loader=bhyve-load`
- Rebooting from inside the guest are handled fine.
- [ ] I have observed this with FreeBSD 10.3 and pfSense 2.3 guests.

If `loader=grub-bhyve` && `persist=1`
- Running `reboot` from inside the guest brings down the bhyve process but the vmm remains.
- &nbsp;&nbsp;&nbsp;&nbsp;If `iohyve start grub-guest` is then ran, problems arise. Error messages get dumped to the screen until you start manually killing processes. The error message is mostly "`bhyve: could not activate CPU 0: Device busy`" but other messages do display if you let it sit long enough.
- &nbsp;&nbsp;&nbsp;&nbsp;OR if `iohyve destroy grub-guest` is then ran instead, the guest reboots as expected.
- [ ] I have observed this with RHEL 7 guests and Debian 8 guests.

If `loader=grub-bhyve` && `persist=2`
- Running `reboot` from inside the guest brings down the bhyve process and also the vmm instance.
- [ ] I have observed this with RHEL 7 guests and Debian 8 guests.

**Comment by corny** [comment]
Host and guest are both FreeBSD 10.3. I use the defaults `loader=bhyveload` and `persist=1`.
Edit: This combination works for me!

**Comment by corny** [comment]
I have to correct my last response: `loader=bhyveload` and `persist=1` works for me.

**Comment by pr1ntf** [comment]
Automatic restarting of guests does happen to be wonky from time to time. 
This will need to be looked at for simplicity sake, and also documented for clarity. 
I will add this to the roadmap as a reminder to work on it. 

Since this seems to be working for you now, I am closing the issue.
