### ISSUE TITLE
Adjust ZFS cache settings

### ISSUE THREAD

**Issue by corny** [pr1ntf/iohyve#137]
The cache settings for the ZFS dataset should be set to `metadata` to not cache data of guests twice.

```
zfs set primarycache=metadata $pool/iohyve/$name/disk0
zfs set secondarycache=metadata $pool/iohyve/$name/disk0
```

**Comment by EpiJunkie** [comment]
How do you mean twice?

**Comment by corny** [comment]
The guest OS has already caches for the filesystem. If the host caches it as well data is cached twice.

**Comment by EpiJunkie** [comment]
Do you still think this would be relevant on non-ZFS based guests? Perhaps there should be a tuning section in the documentation?

**Comment by Crest** [comment]
The problem with the default value (caching data and metadata on the host) is that it results in double caching because every guest OS will implement a disk buffer cache of its own. While the ZFS ARC might be a bit smarter than the guest OS it will still double cache most blocks resulting in lots of wasted RAM. Since the guest expects to be responsible for disk caching anyway its easier to restrict the host to metadata caching instead of implementing a way to efficiently share the host ZFS ARC with bhyve guests.

**Comment by churchers** [comment]
Why set secondary cache to metadata, if you have L2ARC, you may as well cache data on it.
Also I'd be wary of blanket setting the cache to metadata only. It's always possible for users to do this themselves by setting it manually on the root iohyve dataset and letting it be inherited if they really want to turn it off.

Metadata caching seems like a simple setting, but it completely removes ZFS' ability to cache any data at all. If an application tries to read a file in 4K chunks, and the dataset is using the default 128k records, you end up reading every record from disk 32 times. See https://forums.freebsd.org/threads/45555/
It's absolutely imperative that any application on a metadata-cache-only dataset is always reading data in block sizes that match the recordsize.

Personally I would generally avoid ZFS on ZFS as much as possible, and I've never really noticed the disk cache on other file systems being much of a memory issue. As mentioned if users really want the memory back they can set primarycache=metadata themselves. It's not my call but I'm not sure this should be done by default.

**Comment by pr1ntf** [comment]
I'm really hesitant to have iohyve touch those kinds of settings. This is more of a custom tweak than a feature in my eyes. 

That being said, I would not be opposed to someone creating a Technical How-To Journal for the [iohyve wiki](https://github.com/pr1ntf/iohyve/wiki).

Feel free to continue discussion in this thread, but iohyve will not be adding this feature, so I am closing the issue.

**Comment by dmke** [comment]
FYI, we've got bitten by this. One of our machines runs a few disk heavy guests (one instance running MongoDB, another running Gitlab CI), and although the total RAM configured for all guests is well below the machine's installed RAM, we've seen a steady increase in swap usage:

![image](https://user-images.githubusercontent.com/327411/43819923-f5e85a1c-9ae4-11e8-8601-cdbe72e42001.png)

Restarting the guests didn't help much (you can see the orange line drop a few times). In the end, only rebooting the host machine seemed to help for a bit (but doing that once a month is not an option).

While it may be possible to disable disk caches in the guest OS, this is certainly not an easy task, and it varies wildly from OS to OS (even from kernel to kernel), we've gone the easier route and disabled the cache on the guest volumes.

So far we're not swapping, and as a bonus we're running with reduced load:

![image](https://user-images.githubusercontent.com/327411/43820443-94d4518e-9ae6-11e8-9bfc-7730d7b6e4d6.png)

Maybe the readme/wiki could remind users that ZFS will by default cache disk pages, in addition to the guest OS disk caching mechanisms? If you want, I can draft a little block of text for that.

**Comment by dmke** [comment]
Here's a draft for https://github.com/pr1ntf/iohyve/wiki/Performance-Tips (or similar):

````markdown
# Performance Tips

> **Please note: you execute any commands listed here on your own risk.**

## ZFS Caching

As you may know, ZFS caches disk pages in memory (using [ARC][] and
[L2ARC][]). You may also know that any modern OS does this as well. When
running a modern OS from a ZFS volume, like iohyve does, this may induce
a kind of double caching: a program inside your guest accessing the disk
causes the guest OS to cache that page in memory, and in turn the guest
OS accessing the disk is observed by ZFS on the host machine.

Depending on the workload, this might introduce a performance penalty.
In general, the impact is higher for disk heavy loads, like database
servers.

[ARC]: https://www.freebsd.org/doc/handbook/zfs-term.html#zfs-term-arc
[L2ARC]: https://www.freebsd.org/doc/handbook/zfs-term.html#zfs-term-l2arc

If this is an issue for you, you can workaround this either by disabling
the disk cache in your guests (which varies wildly from OS to OS), or by
disabling the ZFS cache on your host (on a guest-by-guest basis).

First, get a list of the volumes for the guest's disks (substitute
`$name` with the guest's name):

```sh
zfs list -o name | grep -E "iohyve.*$name/disk"
```

This should print out something like

```
zroot/iohyve/$name/disk0
```

To disable the cache, run these commands:

```sh
zfs set primarycache=metadata zroot/iohyve/$name/disk0
zfs set secondarycache=metadata zroot/iohyve/$name/disk0
```

Note: using `{primary,secundary}cache=none` is not recommended.

### Further Reading

- Ch. 19.6 [Advannced Topics](https://www.freebsd.org/doc/handbook/zfs-advanced.html)
  in the [FreeBSD Handbook](https://www.freebsd.org/doc/handbook/)
- [ZFS](https://wiki.freebsd.org/ZFS) and
  [ZFS Tuning Guide](https://wiki.freebsd.org/ZFSTuningGuide) in the
  FreeBSD wiki
- original [issue](https://github.com/pr1ntf/iohyve/issues/137)
  describing this as a problem.
````

**Comment by reelsense** [comment]
I had this issue with a heavily used Yacy Search index VM. I was using Virtualbox though. Caching was what was causing issues.
