### ISSUE TITLE
Install hangs when install ubuntu 15.10

### ISSUE THREAD

**Issue by optilude** [pr1ntf/iohyve#139]
Hi,

I'm on newly updated stable FreeNAS 9.10, and I'm trying to run ubuntu 15.10 server edition in a bhyve.

```
$ iohyve version
iohyve v0.7.3 2016/01/08 Bear in a Datacenter Edition
```

After some basic setup:

```
$ kldload vmm
$ kldload ndm
$ iohyve cpiso path/to/ubuntu-15.10-server-amd64.iso 
$ iohyve setup pool=NAS
$ ln -s /mnt/iohyve /iohyve
```

I now have:

```
$  zfs list | grep -i iohyve
NAS/iohyve                                                   622M  1.02T    96K  /mnt/iohyve
NAS/iohyve/Firmware                                           96K  1.02T    96K  /mnt/iohyve/Firmware
NAS/iohyve/ISO                                               621M  1.02T   621M  /mnt/iohyve/ISO
NAS/iohyve/ISO/ubuntu-15.10-server-amd64.iso                  96K  1.02T    96K  /mnt/iohyve/ISO/ubuntu-15.10-server-amd64.iso
```

Then to create a guest:

```
$ iohyve create devbox 50G
$ iohyve set devbox loader=grub-bhyve os=debian ram=2048M cpu=2
```

```
$ iohyve getall devbox
Getting devbox props...
os           debian
boot         0
ram          2048M
name         devbox
cpu          2
loader       grub-bhyve
tap          tap0
con          nmdm0
description  Sun
bargs        -A_-H_-P
autogrub     \n
persist      1
size         50G
```

At this point, I try to run the `install` command, and it never exits:

```
$ iohyve install devbox ubuntu-15.10-server-amd64.iso 
Installing devbox...
```

I can see some processes running, which never exit:

```
3785  0  S+   0:00.01 /bin/sh /usr/local/sbin/iohyve install devbox ubuntu-15.10-server-amd64.iso
13829  0  R+   0:10.83 grub-bhyve -m /iohyve/devbox/device.map -r cd0 -M 2048M ioh-devbox
```

Am I doing something wrong?

For comparison, if I use `ubuntu-14.04-server-amd.iso`, it seems to work.

**Comment by optilude** [comment]
I seem to get the same kind of behaviour with ubuntu 14.04 _after_ the first boot, e.g. if I abort the installer and restart or if it completes and then reboots at the end. The `iohyve console` is empty and the `grub-bhyve` process runs forever and the "Running" status stays as "NO".

**Comment by EpiJunkie** [comment]
Well done! There would be no war in the world if all GitHub issues where opened with this verbosity. Thank you.

Above you used `kldload ndm` when the command is `kldload nmdm`, might explain why the console is empty. Although it does sound like you are getting part way through the installer.

I ran the same config as you mentioned above with success. Installed on a traditional partition scheme (no LVM), booted 2nd and 3rd time without issue. That said I did have to run `iohyve destroy devbox` after the installer finished and attempted to reboot. This deletes the VMM instance.

Also there is a new version of iohyve, 0.7.5.

**Comment by optilude** [comment]
:-)
I think the ndm/nmdm thing is just a typo in the GitHub issue. 
I tried again on 14.04 with non-LVM and putting Ubuntu's grub on /dev/sda1 instead of /dev/sda. I'm able to restart it now. If these are important, the readme didn't mention them I don't think!
15.10 is still a no go, won't boot into installer. Maybe the installer is different?
Are there logs anywhere?

Regards,
Martin

```
_____________________________
```

**Comment by EpiJunkie** [comment]
The installer may be different but I did try `iohyve install bguest ubuntu-15.10-server-amd64.iso` on my own machine and it installed and booted fine. It is running on FreeBSD 10.3, not on FreeNAS. It really seems like it is something unique to your machine.

Could you post the output from the following commands: `iohyve list`, `ps -aux | grep devbox`, and `kldstat`?

For what it worth, the install disc I used has these hashes:

```
root@bhost:~ # md5 ubuntu-15.10-server-amd64.iso
MD5 (ubuntu-15.10-server-amd64.iso) = fb4eef05edcabfc5cccd4cb44f3f9b48
root@bhost:~ # sha512 ubuntu-15.10-server-amd64.iso
SHA512 (ubuntu-15.10-server-amd64.iso) = a29643882d1ee28a289c8228116f9ece469bdd385dba2adb3ec3b3b2f8fc2ee79b3ec17e7890639b7e3cba5a64de670ed4355fe3b51f209dc1151c9ae9bf9e21
```

**Comment by optilude** [comment]
Let me try tomorrow when back at my Mac
Thanks for the quick reply!
Regards,
Martin

On Sun, Apr 17, 2016 at 3:59 PM -0700, "Justin D Holcomb" notifications@github.com wrote:

The installer may be different but I did try iohyve install bguest ubuntu-15.10-server-amd64.iso on my own machine and it installed and booted fine. It is running on FreeBSD 10.3, not on FreeNAS. It really seems like it is something unique to your machine.

Could you post the output from the following commands: iohyve list, ps -aux | grep devbox, and kldstat?

For what it worth, the install disc I used has these hashes:

root@bhost:~ # md5 ubuntu-15.10-server-amd64.iso
MD5 (ubuntu-15.10-server-amd64.iso) = fb4eef05edcabfc5cccd4cb44f3f9b48
root@bhost:~ # sha512 ubuntu-15.10-server-amd64.iso
SHA512 (ubuntu-15.10-server-amd64.iso) = a29643882d1ee28a289c8228116f9ece469bdd385dba2adb3ec3b3b2f8fc2ee79b3ec17e7890639b7e3cba5a64de670ed4355fe3b51f209dc1151c9ae9bf9e21

**Comment by pr1ntf** [comment]
I heard there's a newer version of iohyve in the FreeNAS ports. It should be 0.7.5 "Tennessee Cherry Moonshine Edition." This version has better GRUB guest support. 

You said you were already aware, but do note that Ubuntu likes to default to LVM installs, requiring your `os` property to be `os=d8vm`. 

With the updated iohyve version and the `d8lvm` setting I, too, am able to boot into the Install ISO just fine. 

I also noticed you ran the `cpsio` command before setting up your pool and linking, that may cause some issues as well. you may want to `rmiso` and try again. 

Also, as @EpiJunkie pointed out, nice work on giving us all the info we need, it's really a huge help!

:octopus:

**Comment by allenmchan** [comment]
I saw this ticket and decided to test also since i will eventually use 15.10.
I am also on Freenas 9.10.
Installation just hangs at installing.... 
The server is idling with < 1 load average. 

```

[root@freenas] ~/iohyve# iohyve version
iohyve v0.7.5 2016/04/14 Tennessee Cherry Moonshine Edition

[root@freenas] ~/iohyve# iohyve list
Guest            VMM?  Running  rcboot?  Description
ubuntu1510test   YES   NO       NO       Sun Apr 17 22:49:57 PDT 2016
zoneminder001    YES   YES      NO       Fri_Apr__8_11:43:29_PDT_2016
zoneminderdb001  YES   YES      NO       Fri_Apr__8_20:34:51_PDT_2016

[root@freenas] ~/iohyve# iohyve getall ubuntu1510test
Getting ubuntu1510test iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm2
cpu            1
description    Sun Apr 17 22:49:57 PDT 2016
install        yes
loader         grub-bhyve
name           ubuntu1510test
net            igb1
os             d8lvm
persist        1
ram            1024M
size           50G
tap            tap2



```

**Comment by pr1ntf** [comment]
@allenmchan Nothing appears at the console (`iohyve console ubuntu1510test` from a different terminal)? Sometimes you need to interact with the GRUB menu on Ubuntu guests. 

If nothing is at the console, can you run `iohyve forcekill ubuntu1510test` to kill off the grub-bhyve process and set `iohyve set ubuntu1510test os=default` and tell me what's at the console?

**Comment by Tom-Fawcett** [comment]
My one bit of advice is that older versions of iohyve did have some bugs around the importing of ISOs (though I unfortunately don't have time right this second to check the code of the version you are using).

With that I would check the the paths specified in your device.map are valid for your system.

**Comment by pr1ntf** [comment]
0.7.5 is the most recent version.

**Comment by Tom-Fawcett** [comment]
Yep :) sorry that was aimed at @optilude who said he was on 0.7.3.

**Comment by pr1ntf** [comment]
:+1: :octopus:

**Comment by allenmchan** [comment]
Interesting. My previous experience with deploying the first two VMs were different. The install command would complete and I would get the command prompt again. Then i run the console command to go through the installer UI of Ubuntu. Let me test this different way.

**Comment by pr1ntf** [comment]
Unfortunatly, the new way we utilize grub-bhyve will fail if it's run as a daemon. 
I'm doing more testing and filing a bug report on this issue soon.

**Comment by allenmchan** [comment]
So just an update on the original topic. I ran forcekill and deleted the VM. After redeployment, i was able to install 15.10 on Freenas 9.10 using iohyve 0.7.5

**Comment by pr1ntf** [comment]
Good to hear. I have added feedback if `grub-bhyve` is used to let the user know the terminal will sometimes appear to hang [here](https://github.com/pr1ntf/iohyve/blob/master/iohyve#L524).

**Comment by allenmchan** [comment]
Should probably mention that you will need to open a 2nd terminal to console in when the original terminal is hung on the installation command

**Comment by pr1ntf** [comment]
Should I reword? Right now it reads:

```
echo "GRUB Process does not run in background...."
echo "If your terminal appears to be hanging, check iohyve console $name to complete GRUB process..."
```

**Comment by allenmchan** [comment]
Even with that message, i believe people would instinctly wait for the command prompt to come back. Ctrl -C to term is probably the next 2nd nature thing a person would do and that is probably a bad idea. I would just add something to say open a 2nd terminal and run the console command to complete the GRUB process.

**Comment by pr1ntf** [comment]
Reworded.

**Comment by allenmchan** [comment]
Looks good to me. Hopefully the issue is resolved for the original poster

**Comment by optilude** [comment]
I have 14.04 working now and this doesn't look like a bug so happy for this to be closed. I'll try some more things later, and will reopen if there looks to be a real issue.
Thanks for all the help!
Regards,
Martin

On Mon, Apr 18, 2016 at 12:41 AM -0700, "Allen Chan" notifications@github.com wrote:

Looks good to me. Hopefully the issue is resolved for the original poster

**Comment by optilude** [comment]
Confirmed as an issue with the ISO (somehow it was 96kb only)
