### ISSUE TITLE
Some hosts will not load tap module.

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#141]
During the startup process, some hosts will not load the `if_tap` kernel module when `sysctl net.link.tap.up_on_open=1` is ran.

This applies to the `iohyve setup net=[iface]` function. If you roll your own `sysctl.conf` file you should be fine.

**Comment by churchers** [comment]
> some hosts will not load the if_tap kernel module when sysctl net.link.tap.up_on_open=1 is ran.

If the `if_tap` kernel module is not loaded, the `tap` sysctl variables will not exist, and trying to set them will just report `unknown oid`. `sysctl` will never attempt to load anything.

If users have tap interfaces configured in `/etc/rc.conf`, the module should be loaded automatically when the rc system creates those interfaces. I'd expect this problem to occur if there are no tap devices in `rc.conf`.

I would say the best solution would be to modify the `kmod=1` code so it loads `vmm/nmdm/if_tap/if_bridge`, if they are not already loaded. Does also mean that `kmod=1` should always come before `net=...` in the rc variables.

**Comment by pr1ntf** [comment]
Thanks for your input!
This is indeed the case, and a work around is in the works for adding the modules `if_bridge` and `if_tap` to the `kmod=` function. 

iohyve used to be hardcoded to set up `tap0` in the `net=` function not that long ago. This is now just rolling around to my radar. 

This issue was created more as a reminder to add those (and clean up the `kmod=` function itself) next time I sat down to work on iohyve. I didn't see it fit into the roadmap since it's an easy fix. 

:octopus:

**Comment by jbergstroem** [comment]
FWIW I ran into this today as well on a pretty fresh 10.3 system. No manual `tap0` in `rc.conf`, so iohyve gave similar output when I ran setup.

**Comment by pr1ntf** [comment]
This will indeed be the case until a fix is pushed for the `kmod=[0/1]` function. Until then, you can add the following lines to your `/boot/loader.conf` file:

```
if_bridge_load="YES"
if_tap_load="YES"
```

**Comment by pr1ntf** [comment]
This has been added.
