### ISSUE TITLE
Use different `grub.cfg` for custom ostypes

### ISSUE THREAD

**Issue by jbergstroem** [pr1ntf/iohyve#145]
It'd be convenient to have different `grub.cfg`'s for custom installs, for instance `grub.cfg` and `grub-install.cfg`. That way less tinkering is required between runs.

**Comment by jbergstroem** [comment]
To expand; you can pass which grub config you want to read through `-g grub-install.cfg`.

**Comment by EpiJunkie** [comment]
Is having the `os` type set as `custom` and then changing the filename for the active grub configuration to `grub.cfg` to much work? Are you installing so often that this is actually practical? Does `iohyve install` not fulfill your needs? As they are effectively two different grub configurations.

I do not see how this can be made more efficient with my current work flow, somewhere the change needs to be made and I think a file rename is the simplest; easier than setting `iohyve` properties to store the `grub.cfg` file name to use. What is your work flow like? Thoughts/suggestions?

And again, thank you for the feedback to this project.

**Comment by jbergstroem** [comment]
I think there's a use case for this seeing how they (install or run) solve two different problems. Perhaps check if `grub-install.cfg` exists and use `grub.cfg` if it doesn't? If you look at this from a scripting point of view (lets say you want to set up a bhyve host through ansible or some other orchestration), it becomes tedious since you're introducing state. The alternative would be installing two files instead of one.

**Comment by pr1ntf** [comment]
The custom `grub.cfg` stuff is meant to be fully customized by the end user, so no work will be done by iohyve itself. 

Also note that the way it's written right now, iohyve searches for the file `grub.cfg`. This way you can have two `grub.cfg` files if you have to reinstall often. Maybe have one named `install-grub.cfg` and one named `installed-grub.cfg` and naming it `grub.cfg` when using the one you need.
