### ISSUE TITLE
os=default install doesn't pass root path

### ISSUE THREAD

**Issue by jbergstroem** [pr1ntf/iohyve#148]
..which in turn then doesn't load `grub.cfg`.

**Comment by EpiJunkie** [comment]
The os=default is caught by the catch all `else` statement and the root path is specified.

During installation the root path is on the optical media specified by `-r cd0`:

```
[Line 667]
            else
                printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
                printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
                grub-bhyve $wire_memory -m /iohyve/$name/device.map -r cd0 -c /dev/${con}A -M $ram ioh-$name
            fi

```

After installation the root path is on the harddrive specified by `-r hd0,msdos1`:

```
        elif [ $install = "no" ]; then
...
[Line 711]
            else
                printf '\(hd0\)\ /dev/zvol/'$disk'\n' > /iohyve/$name/device.map
                printf '\(cd0\)\ '$media'\n' >> /iohyve/$name/device.map
                grub-bhyve $wire_memory -m /iohyve/$name/device.map -r hd0,msdos1 -c /dev/${con}A -M $ram ioh-$name
            fi
```

What makes you say it is not being loaded? If you are experiencing the issue with an unlisted OS let me know, I would love to figure it out and add support.

**Comment by jbergstroem** [comment]
Unfortunate use of words; by `root path`, I was referring to the directory where `grub-bhyve` is looking for `grub.cfg`. On the same lines you just referenced there is no `-d` to be found whereas all other cases does pass it. I will file a PR shortly.

**Comment by EpiJunkie** [comment]
I know `-d` has a default assumed value which I think is `/boot/grub` but I am not 100% sure.

**Comment by jbergstroem** [comment]
Yes, that's correct.

**Comment by pr1ntf** [comment]
The default property is a last ditch effort to give a `GRUB CLI` environment so you can load the kernel and initramfs manually. If you are having issues with a specific OS, please open a feature request so we can get to work adding the specific OS to the giant nested `IF/THEN` monstrosity.
