### ISSUE TITLE
auto-reading `grub.cfg` doesn't seem to work

### ISSUE THREAD

**Issue by jbergstroem** [pr1ntf/iohyve#149]
No matter what I try, (`-d` with `grub.cfg` in the same dir, passing `-g`, etc) `grub-bhyve` doesn't seem to read `grub.cfg`. Piping `grub.cfg` works just fine:

``` bash
$ cat /iohyve/test/grub.cfg | \
  grub-bhyve -m /iohyve/test/device.map -d /iohyve/test -r cd0 -M 4096M ioh-test
```

Guessing this should be filed upstream at `grub-bhyve` somewhere, but seeing how this was recently changed in `iohyve` I wanted to see if it's working for anyone else.

Info:

``` bash
$ uname -v
FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC

 $ iohyve version
iohyve v0.7.5 2016/04/14 Tennessee Cherry Moonshine Edition

$ grub-bhyve --version
grub-bhyve (GRUB-BHYVE) 2.00:0.40
```

**Comment by EpiJunkie** [comment]
What OS is the guest? I have tried this on several Linux distros with success. In my experience, booting problems with supported guests typically come down to either residual install/start attempts or installation media corruption; such as the VMM was never being destroyed after a shutdown or a failed reboot.

**Comment by jbergstroem** [comment]
@EpiJunkie will test with your gentoo branch next since I have a gentoo install image laying around. Get back to you shortly (and thanks for helping out).

**Comment by EpiJunkie** [comment]
No problem. Thanks for testing it. Let me know if any adjustments need to be made.

**Comment by jbergstroem** [comment]
Ok, so after @EpiJunkie elaborating on `-r host` I figured it out; I assumed that `grub.cfg` was relative to `-d` when it in fact needs both. I'll see if I can improve the readme to have others avoid this. Thanks.
