### ISSUE TITLE
Could not create VM ioh

### ISSUE THREAD

**Issue by fjfo** [pr1ntf/iohyve#151]
hi all,
I'm using FreeNAS 9.10 stable
`[root@freenas] ~# uname -a`
`FreeBSD freenas.local 10.3-RELEASE FreeBSD 10.3-RELEASE #0 f935af8(freebsd10): Tue Apr 26 08:30:39 PDT 2016     root@build.ixsystems.com:/tank/home/nightlies/build-freenas9/_BE/objs/tank/home/nightlies/build-freenas9/_BE/trueos/sys/FreeNAS.amd64  amd64`

$iohyve version
`iohyve v0.7.5 2016/04/14 Tennessee Cherry Moonshine Edition`

$iohyve list
`Guest          VMM?  Running  rcboot?  Description`
`debianvm       NO    NO       NO       Fri Apr 29 00:55:51 ICT 2016`

$iohyve getall debianvm
`Getting debianvm iohyve properties...`
`bargs          -A_-H_-P
boot           0
con            nmdm0
cpu            1
description    Fri Apr 29 00:55:51 ICT 2016
install        yes
loader         grub-bhyve
name           debianvm
os             debian
pcidev:1       passthru,2/0/0
persist        1
ram            2048M
size           8G
tap            tap0`

$iohyve isolist
`Listing ISO's...`
`debian-8.4.0-amd64-netinst.iso`

but I can not install ISO file with command:
$iohyve install debianvm debian-8.4.0-amd64-netinst.iso
`Installing debianvm...`
`Could not create VM ioh-debianvm`
`Error in initializing VM`
`vm_create: Device not configured`

What am i missing here?
Please take a look and help, thank.

**Comment by moogle19** [comment]
Hi,
can you tell me which CPU you are using in your system? Maybe it does not support all needed features for bhyve.

**Comment by fjfo** [comment]
$sysctl hw.model hw.machine hw.ncpu
`hw.model: Intel(R) Core(TM)2 Duo CPU     E4600  @ 2.40GHz`
`hw.machine: amd64`
`hw.ncpu: 2`

$grep -i cpu /var/run/dmesg.boot
`CPU: Intel(R) Core(TM)2 Duo CPU     E4600  @ 2.40GHz (2400.05-MHz K8-class CPU)`
`FreeBSD/SMP: Multiprocessor System Detected: 2 CPUs`
`cpu0 (BSP): APIC ID:  0`
`cpu1 (AP): APIC ID:  1`
`cpu0: <ACPI CPU> on acpi0`
`cpu1: <ACPI CPU> on acpi0`
`coretemp0: <CPU On-Die Thermal Sensors> on cpu0
est0: <Enhanced SpeedStep Frequency Control> on cpu0
coretemp1: <CPU On-Die Thermal Sensors> on cpu1
est1: <Enhanced SpeedStep Frequency Control> on cpu1
SMP: AP CPU #1 Launched!`

Thank for your concern.

**Comment by moogle19** [comment]
Okay. Thats the problem. Your CPU doesn't support the virtualization features needed by bhyve.
You can read about the requirements for CPU's here: https://wiki.freebsd.org/bhyve
Basically your CPU must support VT-x and EPT (in the Intel world) to run bhyve.

**Comment by fjfo** [comment]
omg, 
thank you
