### ISSUE TITLE
Check if CPU is supported by bhyve

### ISSUE THREAD

**Issue by moogle19** [pr1ntf/iohyve#152]
It would be nice to check, if the current CPU is supported by bhyve. (see #151)
Would it be enough to run `cat /var/run/dmesg.boot | grep POPCNT` or are there better features to determine if this CPU is supported?
The bhyve wikipage states bhyve supports **most** CPUs which report `POPCNT`.

Or would it be better to run `cat /var/run/dmesg.boot | grep VT-x | grep EPT` to check if it supports EPT.

**Comment by Johanhen** [comment]
Op 29/04/16 om 10:54 schreef Kevin:

> It would be nice to check, if the current CPU is supported by bhyve.
> (see #151 https://github.com/pr1ntf/iohyve/issues/151)
> Would it be enough to run |cat /var/run/dmesg.boot | grep POPCNT| or
> are there better features to determine if this CPU is supported?
> The bhyve wikipage states bhyve supports _most_ CPUs which report
> |POPCNT|.
> 
> Or would it be better to run |cat /var/run/dmesg.boot | grep VT-x |
> grep EPT| to check if it supports EPT.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pr1ntf/iohyve/issues/152
> 
> I do not know if the port can check this.
> It would be nice if at the install stage of the port the port already
> checks if it can run on the machine.
> Then add the option to either install anyway or just abort.

regards
Johan

**Comment by moogle19** [comment]
I was more thinking about adding a check to `iohyve setup` not during installation of the port.
Something like `Your CPU is propably not supported by bhyve, etc... Proceed anyway? [y/N]`

**Comment by pr1ntf** [comment]
I think it should be kept in `iohyve setup` but doesn't `kldload` throw an error if it can't load `VMM`? If you can't load the kernel module, you shouldn't be running iohyve?

**Comment by moogle19** [comment]
Yes, according to the wiki it throws:

```
# kldload vmm
vmx_init: processor does not support VMX operation
module_register_init: MOD_LOAD (vmm, 0xffffffff81e17169, 0) error 6
```

if the processor doesn't support EPT.

**Comment by moogle19** [comment]
But I think a `Your CPU is not supported by bhyve` looks a bit friendlier to the user.

**Comment by skarekrow** [comment]
Catching that error is probably more useful then checking dmesg. If VMM thinks it’s supported, then who are we to argue?
- Brandon
  On Fri, Apr 29, 2016 at 4:20 AM, Kevin notifications@github.com wrote:
  But I think a Your CPU is not supported by bhyve looks a bit friendlier to the user.

**Comment by moogle19** [comment]
Yes, that's a good point.
But I however think, a warning would be helpful.

If you install iohyve, configure your virtual machine and download your iso, only to find out it does not run on your machine would be a bit frustrating.
Something like `Your CPU is propably not supported by bhyve, etc... Proceed anyway? [y/N]` when running `iohyve setup` wouldn't be that bad, right?

**Comment by pr1ntf** [comment]
Continue discussion in #153
