### ISSUE TITLE
Validation of arguments to prevent unexpected behaviour

### ISSUE THREAD

**Issue by mariusvw** [pr1ntf/iohyve#156]
For example, if I run:

```
iohyve start
```

I run into:

```
# iohyve start
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
[: -: unexpected operator
Starting ... (Takes 15 seconds for FreeBSD guests)
Usage: grep [OPTION]... PATTERN [FILE]...
```

After this the console becomes unresponsive.

Advice (when I have the time I'll look into it) is to validate if the argument contains valid data.

**Comment by moogle19** [comment]
Hi, 
started that already, but I am currently waiting for my PR #142  to be merged until I continue working on it.

**Comment by mariusvw** [comment]
To me it looks like this can simply be build into the __parse_cmd function. I'll add it to the current version, later on merge it into the lib separated version if it will be merged. Personally I don't mind the one-file solution like it works now.

**Comment by pr1ntf** [comment]
Yeah it looks like @moogle19 had already done some work on this previously. I'm going to close this issue for now, and we can discuss in the PR once #142 get's merged. 

Again, thanks for your input!
