### ISSUE TITLE
Debian & Ubuntu Iohyve

### ISSUE THREAD

**Issue by pieterjanvu** [pr1ntf/iohyve#157]
Suggest a bit more info to be added to iohyve debian/ubuntu installation instructions:
After:
`iohyve install debguest debian-8.2.0-amd64-i386-netinst.iso`
I had to do the following as the command appears to be stuck.
1. Open a separate terminal, type:
`iohyve console debguest`
2. nothing will show, but just press "enter" to get past the grub menu boot. It will select default.
3. Then iohyve install command completes & you can see in console window to proceed with installation.

Not sure if anyone else is experiencing this issue, but adding something like this to the install instructions could help some people trying to install debian/ubuntu and potentially others stuck on grub prompt.

**Comment by pieterjanvu** [comment]
Some more playing around, I would suggest opening the console in another command prompt first, then entering the install command in the original prompt. This enables you to see the full grub prompt in console rather than having a blank console because you logged in too late.

**Comment by pr1ntf** [comment]
We've noticed this behavior as well. 
When the `loader` is set to `grub-bhyve` iohyve will spit out:

```
GRUB Process does not run in background....
If your terminal appears to be hanging, check iohyve console $name in second terminal to complete GRUB process...
```

This was [added](https://github.com/pr1ntf/iohyve/blob/master/lib/ioh-guest#L250) recently. 

Thanks for the input!
