### ISSUE TITLE
To exit console, it is "~." not "~~."

### ISSUE THREAD

**Issue by pieterjanvu** [pr1ntf/iohyve#158]

**Comment by pieterjanvu** [comment]
Not sure if anyone else is experiencing this? Perhaps worth updating the information on the site/iohyve info on console login?

**Comment by moogle19** [comment]
If you work directly on the host, that is correct.
But if you are ssh'd into the host, where iohyve runs, you have to use `~~.` , because `~.` kills you ssh session.

**Comment by pieterjanvu** [comment]
Ok. makes sense.
Oddly enough, ~. doesn't kill a putty session, but I'll put that down to windows abnormalities.
