### ISSUE TITLE
Not working with pci passthru

### ISSUE THREAD

**Issue by corv89** [pr1ntf/iohyve#166]
Passthru is not working on 10.3 (FreeNAS)

Without setting bargs="-S" I get the error "passthru requires guest memory to be wired".

With bargs="-A_-H_-P_-S" the vm won't run.

**Comment by pr1ntf** [comment]
Odd, `wired memory` should now be in `bhyve` as of `FreeBSD 10.3-RELEASE`.

> With bargs="-A_-H_-P_-S" the vm won't run.

Can you elaborate on what error you are getting? This is working for me (I'm not using `FreeNAS` though)

The output of `iohyve version` and `uname -a` would also be quite helpful here.

**Comment by corv89** [comment]
freebsd-version is 10.3-RELEASE
iohyve version is v0.7.3

I’ll update FreeNAS now and see if it bumps the version

**Comment by corv89** [comment]
After updating I've got iohyve version v0.7.5

```
# iohyve install pfsense pfsense23.iso
Installing pfsense...

# iohyve list
Guest    VMM?  Running  rcboot?
pfsense  YES   NO       NO

# iohyve console pfsense
Connected
(unresponsive)

# iohyve start pfsense
Starting pfsense... (Takes 15 seconds for FreeBSD guests)
vm_setup_memory: File exists
Unable to setup memory (17)

# iohyve list
Guest    VMM?  Running  rcboot?
pfsense  NO    NO       NO
```

Logs show tap device go up.

**Comment by corv89** [comment]
I've attached the console before running `iohyve install` and I can see the pfsense bootloader now. It loads the kernel and gets stuck at "Booting..." Not running according to iohyve list.

**Comment by EpiJunkie** [comment]
Will you post your output from: `cat /var/run/dmesg.boot | grep ppt` and from `iohyve getall pfsense`? Thanks.

**Comment by corv89** [comment]
`cat /var/run/dmesg.boot | grep ppt` 
is empty

I tried putting the relevant device in /boot/loader.conf as pptdevs="8/0/0" but there is no change to `pciconf -v -l`

The device I'm attempting to passthru is Intel i210 "Using MSIX interrupts with 5 vectors" according to dmesg output.

```
# iohyve getall pfsense
Getting pfsense iohyve properties...
autogrub       \n
bargs          -A_-H_-P_-S
boot           0
con            nmdm0
cpu            1
description    Tue May 10 16:59:24 CET 2016
install        yes
loader         bhyveload
name           pfsense
os             default
pcidev:1       passthru,8/0/0
persist        1
ram            1024M
size           8G
tap            tap0
```

Thank you for your help

**Comment by EpiJunkie** [comment]
With FreeNAS, you have to add the changes for the `/boot/loader.conf`  in the [WebUI as a tunable](https://doc.freenas.org/9.3/freenas_system.html#tunables). FreeNAS uses `grub` to boot so when you make changes to the `/boot/loader.conf` file, the `grub` configuration files need to be rebuilt. The WebUI takes care of this.

**Comment by corv89** [comment]
Thank you for the promising suggestion.

I tried to pass tunables variable "pptdevs" as value "8/0/0". 
`pciconf -t -l` is still showing igb0@pci0.

I'm not sure if these tunables are documented somewhere.

**Comment by corv89** [comment]
Inspecting /boot/loader.conf.local `pptdevs="8/0/0"` shows up.

**Comment by EpiJunkie** [comment]
Is this NIC card a multi-port device? You may need to add the other port on devices if they share the same root PCI address. So if there is a `8/0/1` device, it will have to be added as well.

**Comment by corv89** [comment]
I've got
`igb1@pci0:8:0:0`
and
`igb0@pci0:7:0:0`

**Comment by EpiJunkie** [comment]
_For the sake of thoroughness_, have you rebooted since changing the tunable... 

Is VT-x turned on in the BIOS? Is VT-x available on your motherboard and CPU combination? Post your output from this: `cat /var/run/dmesg.boot | grep -B 100 "real memory" | grep -v "real memory" | grep -A 20 "CPU:"`.

**Comment by corv89** [comment]
I did reboot after setting the tunable. 👍 

```
# cat /var/run/dmesg.boot | grep -B 100 "real memory" | grep -v "real memory" | grep -A 20 "CPU:"
CPU: Intel(R) Atom(TM) CPU  C2750  @ 2.41GHz (2416.82-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x406d8  Family=0x6  Model=0x4d  Stepping=8
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x43d8e3bf<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,EST,TM2,SSSE3,CX16,xTPR,PDCM,SSE4.1,SSE4.2,MOVBE,POPCNT,TSCDLT,AESNI,RDRAND>
  AMD Features=0x28100800<SYSCALL,NX,RDTSCP,LM>
  AMD Features2=0x101<LAHF,Prefetch>
  Structured Extended Features=0x2282<TSCADJ,SMEP,ERMS,NFPUSG>
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID
  TSC: P-state invariant, performance statistics
```

**Comment by EpiJunkie** [comment]
Thanks for confirming that.

Do you have the `vmm` kernel module loaded in `/boot/loader.conf` as a tunable? I think that `vmm` loads some of the "blackhole" drivers.

**Comment by corv89** [comment]
I did try that previously.

kldstat shows 

```
32    1 0xffffffff821b0000 1b140b   vmm.ko
33    1 0xffffffff82362000 2ebb     nmdm.ko
```

among others.

**Comment by churchers** [comment]
Intel Ark doesn't mention that Atom having VT-d support. The following from the bhyve wiki shows a way to check if the system does support it

> PCI passthru with bhyve works on systems that have the Intel IOMMU (aka VT-d). This can be determined by seeing if there is a DMAR table in the ACPI tables i.e. acpidump -t | grep DMAR

**Comment by corv89** [comment]
Looks like you're right.
`acpidump -t | grep DMAR`
is empty.

That's a bummer.

**Comment by pr1ntf** [comment]
Thanks for your help @EpiJunkie and @churchers 

Closing issue.
