### ISSUE TITLE
specify volmode / default volmode

### ISSUE THREAD

**Issue by lunetics** [pr1ntf/iohyve#171]
I think there's a usecase of having a configurable volmode, either as iohyve default (or take the sysctl default) or per created machine

E.g. for performance monitoring I would like to monitor the disk-usage via gstat. gstat works with geomproviders only.

Is there any drawback using volmode geom instead of dev? (default sysctl is 1 = geom)

**Comment by pr1ntf** [comment]
There was a time when `volmode=geom` would break things, but that doesn't seem to be the case anymore. 

This is a great idea, we will probably keep `volmode=dev` the default (unless someone convinces us otherwise), but add the ability to change it with a properties setting.

**Comment by pr1ntf** [comment]
This has been added to the [list](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0). Closing issue.
