### ISSUE TITLE
Load 'if_tap' automatically in 'iohyve setup net=xxx0'

### ISSUE THREAD

**Issue by moogle19** [pr1ntf/iohyve#174]
When `if_tap` is not loaded the `sysctl net.link.tap.up_on_open` command always fails with 

```
sysctl: unknown oid 'net.link.tap.up_on_open'
```

That means if you run `iohyve setup pool=tank net=igb0` the sysctl command fails in most cases, because `if_tap` is not loaded.

Should `if_tap` be loaded automatically when `iohyve setup net=xxx0` is run?

**Comment by moogle19** [comment]
This would also make the reordering of arguments in my PR #173 obsolete.

**Comment by pr1ntf** [comment]
I think your checks in #173 do a good job of taking care of this situation. 

Let's only load the kernel modules when the user specifies they want kernel modules loaded.
