### ISSUE TITLE
Move duplicate code into functions for better maintainability

### ISSUE THREAD

**Issue by moogle19** [pr1ntf/iohyve#178]
Currently there is plenty of code duplication.
This should be cleaned up and the duplicate code should be moved into functions.

**Comment by pr1ntf** [comment]
This is a massive undertaking. Let's wait a bit for the dust to settle. There are a lot of changes happening to iohyve right now. Otherwise we are going to be doing the "This PR has conflicts" Dance over and over. 

I'm all for it though.

**Comment by pr1ntf** [comment]
I've been thinking about this one a lot recently. With stuff slowing down again, we should revisit this and start a plan of attack. For starters, we should look at what's going on in `ioh-guest` as a start. Maybe squishing most of that into just a few functions.

**Comment by pr1ntf** [comment]
No movement or discussion in two weeks. Closing ticket. I'm sure we are all aware this needs to be done anyway.
