### ISSUE TITLE
Prefix functions with the name of the file they are in

### ISSUE THREAD

**Issue by mariusvw** [pr1ntf/iohyve#180]
Just an idea to prevent overlapping.

For example in the file ioh-zfs, is it an idea to prefix these functions with **zfs** in the name?

For example:

```
__zfs_get() {
}
```

This might prevent future function overlapping when things get bigger...

Let me know if you'd like to have this and I'll finish up my changes...

**Comment by pr1ntf** [comment]
Moving discussion to #181
