### ISSUE TITLE
Autostart uefi boot

### ISSUE THREAD

**Issue by Davis-A** [pr1ntf/iohyve#185]
VMs started using iohyve uefi instead of iohyve start don't autostart when boot=1.  Is this a bug or lacking the feature to determine they have firmware associated to start with uefi?

**Comment by pr1ntf** [comment]
What iohyve version are you running? The one from GitHub or the one from Ports?
Have you verified the guests can boot via UEFI with `iohyve start $guestname`?

I have not yet tested the iohyve UEFI stuff with booting at RC time yet, as it is still experimental as the [wiki](https://github.com/pr1ntf/iohyve/wiki/UEFI-GOP-and-iohyve) states. Any feedback and console output is greatly appreciated.

**Comment by pr1ntf** [comment]
I am closing out this ticket due to inactivity. If you are still seeing issues, please reply and I'll reopen the issue. Thank you.
