### ISSUE TITLE
Disk resize with snapshots

### ISSUE THREAD

**Issue by lunetics** [pr1ntf/iohyve#186]
When using the resize command, it seems __disk_resize() does not exclude snapshots, resulting in an error:

iohyve resize name disk0 25G
Resizing disk0 to 25G
[: /iohyve/zroot: unexpected operator
cannot set property for 'zroot': 'volsize' does not apply to datasets of this type

**Comment by lunetics** [comment]
Also for roll-back the parent directory needs to be unmounted!

**Comment by pr1ntf** [comment]
Long time no talk. I'm finally closing this issue. 
We are going to completely re-write snapshotting/rollback functions in the near future. 

We are going to have it function much like `zfstools` and also allow automatic snapshotting.
