### ISSUE TITLE
Ignore wrong command

### ISSUE THREAD

**Issue by lunetics** [pr1ntf/iohyve#187]
Sometimes i got a typo and write "iohyve <vm> start" instead of "iohyve start <vm>", resultrs in some shell massacre.

Shouldn't it be possible to just return "command not know" or something?

**Comment by EpiJunkie** [comment]
@lunetics which version of iohyve are you running? The fix was introduced after version 0.7.5 was released. I do not believe 0.7.6 has made it to ports or pkg yet but you can [download the project](https://github.com/pr1ntf/iohyve/archive/master.zip) files, extract, and run `make install`.

**Comment by pr1ntf** [comment]
iohyve version `0.7.6` will hit ports soon, everyone has been on vacation after BSDCan it seems. 

Thanks to some awesome work done by @EpiJunkie @moogle19 and @mariusvw there is now quite a bit more error handling.
