### ISSUE TITLE
guest uefi doesn't exist

### ISSUE THREAD

**Issue by pobkac** [pr1ntf/iohyve#188]
Hello I am having a problem creating a windows VM

I have tried manually running bhyve which gets me to the windows SAC console but goes no further, [no apparent disk activity and minimal CPU utilisation], so it would appear that there is a problem with my windows iso file or bhyve settings but it at least gets somewhere.

I have followed your guide https://github.com/pr1ntf/iohyve/wiki/Running-Windows-Under-iohyve as accurately as I can.  Previously running iohyve v0.7.5 (11.0 alpha2) failed on the cpiso and cpfw commands.

This is on a fresh install of 11.0 Alpha4, iohyve v0.7.6 isolist and fw list resolve the required .iso and .fd files
iohyve output below

root@jupbsd11:/mnt/working/YABS # iohyve uefi WHS2011-1 WHS2011.iso
guest uefi doesn't exist
root@jupbsd11:/mnt/working/YABS # iohyve install uefi WHS2011-1 WHS2011.iso
guest uefi doesn't exist
root@jupbsd11:/mnt/working/YABS # iohyve start WHS2011
guest WHS2011 doesn't exist
root@jupbsd11:/mnt/working/YABS #

root@jupbsd11:/iohyve/WHS2011-1 # iohyve getall WHS2011-1
Getting WHS2011-1 iohyve properties...
bargs          -H_-w
boot           0
con            nmdm1
cpu            1
description    Tue Jun 21 14:20:57 ACST 2016
fw             BHYVE_UEFI_20151002.fd
install        yes
loader         bhyveload
name           WHS2011-1
os             default
persist        1
ram            2048M
size           32G
tap            tap1
template       NO
vnc            NO
vnc_h          600
vnc_ip         127.0.0.1
vnc_tablet     NO
vnc_w          800
vnc_wait       NO
root@jupbsd11:/iohyve/WHS2011-1 #

**Comment by pr1ntf** [comment]
The `uefi` function is now depreciated. Simply set `loader=uefi` and run `iohyve start` or `iohyve install` as normal. That wiki page is currently out of date. However, the man pages and the new [UEFI-GOP](https://github.com/pr1ntf/iohyve/wiki/UEFI-GOP-and-iohyve) instructions should be up to date. 

It also looks like you had a typo in your `iohyve start` command earlier:

```
root@jupbsd11:/mnt/working/YABS # iohyve start WHS2011
guest WHS2011 doesn't exist
root@jupbsd11:/iohyve/WHS2011-1 # iohyve getall WHS2011-1
```

Note you did not add the `-1`. 

Also note that this syntax will not work:

```
iohyve install uefi WHS2011-1 WHS2011.iso
```

**Comment by pobkac** [comment]
awesome! and thanks for the quick response.
and many thanks for the software.  I couldn't do this kind of stuff with out these programs like iohyve

**Comment by pr1ntf** [comment]
Thanks for the detailed bug report and the very kind words! :+1: :sunglasses: :octopus:
