### ISSUE TITLE
create tries to pass invalid arguments to ZFS

### ISSUE THREAD

**Issue by sonnens** [pr1ntf/iohyve#190]
root@cube:~ # iohyve create debian 10gb
Creating debian...
too many arguments
usage:
    create [-pu] [-o property=value] ... <filesystem>
    create [-ps] [-b blocksize] [-o property=value] ... -V <size> <volume>

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
too many arguments
usage:
    create [-pu] [-o property=value] ... <filesystem>
    create [-ps] [-b blocksize] [-o property=value] ... -V <size> <volume>

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow

**Comment by pr1ntf** [comment]
Thanks for the report and bug squash!
