### ISSUE TITLE
iohyve fails to boot guest after host upgrade to 10.3 'passthru requires guest memory to be wired'

### ISSUE THREAD

**Issue by HiddenWolf** [pr1ntf/iohyve#194]
I've just updated my host to FreeBSD 10.3

The host runs one iohyve/hbyve VM, pfsense. This serves as a virtual firewall for my network.
I've passed through the external ethernet adapter to the VM.

After the upgrade, starting the VM fails with 'passthru requires guest memory to be wired'
I've googled, read the manpage, but don't see an obvious solution.

Kindly point me in the right direction.

**Comment by EpiJunkie** [comment]
You will need to append `-S` to current `bargs` parameters for the guest.

**Comment by HiddenWolf** [comment]
iohyve set pfsense bargs="-A -H -P -s"
iohyve start pfsense
invalid pci slot info field -m

**Comment by EpiJunkie** [comment]
"`-s`" is not equal to "`-S`". "`-S`" is used to wired memory, "`-s`" is used to start specifying a PCI slot device which is why you are having the issue. The command should be:

"`iohyve set pfsense bargs="-A -H -P -S"`"

**Comment by HiddenWolf** [comment]
Leads to: "unable to setup memory (17)"

EDIT: Apparently, I need to pass -S to bhyveload as well? 
How do I get iohyve to do that for me?

**Comment by EpiJunkie** [comment]
That should be done automatically.

Which version of iohyve are you running? `iohyve version`

**Comment by HiddenWolf** [comment]
0.7.1, also known as what I ended up with after freebsd-upgrade -r 10.3

**Comment by EpiJunkie** [comment]
You may want to upgrade to the latest version, 0.7.1 does not seem to be tagged here in GitHub. The wire memory functionality was missing in 0.7 and the next tagged version does have it (0.7.3). With the gap it is hard for me to say whether the functionality was there.

**Comment by HiddenWolf** [comment]
Problem is that the VM routes the internet for this machine. it has no
network at the moment.

Any quick and dirty way to get it to work temporarily, so I don't have to
redo my network settings?

**Comment by EpiJunkie** [comment]
Umm, download the zip file of the project [here](https://github.com/pr1ntf/iohyve/archive/master.zip), put on a thumbdrive, and then install on the server manually.

``` shell
unzip master.zip
cd iohyve
make install
```

**Comment by HiddenWolf** [comment]
Finally got the chance to. Problem solved.

**Comment by pr1ntf** [comment]
Rad! I'm glad you got sorted out. 

Thanks @EpiJunkie for filling in!
