### ISSUE TITLE
11Beta1 and fresh install

### ISSUE THREAD

**Issue by anteract** [pr1ntf/iohyve#195]
Get this on install, fresh install of 11 Beta 1 and 0.7.5 from pkg's

 iohyve setup net=igb0
Seting up bridge0 on igb0...
sysctl: unknown oid 'net.link.tap.up_on_open'

**Comment by pr1ntf** [comment]
Try running `iohyve setup kmod=1` first. Or both at the same time `iohyve setup kmod=1 net=igb0`

**Comment by anteract** [comment]
This is the result of your command (both together)... 

iohyve setup kmod=1 net=igb0
Loading kernel modules...
kldload: can't load vmm: module already loaded or in kernel
kldload: can't load nmdm: module already loaded or in kernel
Seting up bridge0 on igb0...
sysctl: unknown oid 'net.link.tap.up_on_open'
ifconfig: create: bad value
ifconfig: BRDGADD igb0: File exists

I'm going to rebuild the kernel, and try again, that sysctl should be there, its in if_tap.c just fine, and not getting passed along.  Will close this if it was a glitch in my build.

**Comment by pr1ntf** [comment]
You also may want to try installing `iohyve` from ports. The version should be `v0.7.6`.

**Comment by anteract** [comment]
Ignore this.. new build of world and all is fine.  the tap device just wasn't there for some reason on this machine.
Thanks.

**Comment by pr1ntf** [comment]
Glad you got it sorted. :+1:
