### ISSUE TITLE
Not listing all VMs

### ISSUE THREAD

**Issue by b4** [pr1ntf/iohyve#197]
This is critical, as it is preventing me from bringing my mailserver up.

root@amethyst:~ # ls /iohyve/pbx.gewt.net/
device.map
root@amethyst:~ # ls /iohyve/mailer.gewt.net/
device.map
root@amethyst:~ # iohyve list
Guest         VMM?  Running  rcboot?  Description
pbx.gewt.net  NO    NO       NO       Sat Feb 27 16:51:07 CST 2016

**Comment by b4** [comment]
Fixed with:

**Comment by b4** [comment]
Fixed with: zfs set iohyve:name=<VM name>

**Comment by pr1ntf** [comment]
Was `mailer.gewt.net` created with `iohyve create`? Also, what version is this? `iohhyve version`

**Comment by b4** [comment]
Yes - the VM was created with iohyve create, but it looks like it was done before a change in ZFS properties.

**Comment by pr1ntf** [comment]
Does this continue to happen on your current version? (Hopefully at  `0.7.6` ;) )

**Comment by b4** [comment]
I haven't created any new VMs yet - I need to know how to use multiple bridges before that happens ;)

**Comment by pr1ntf** [comment]
Can you please test? This would be a serious issue. 
Just running `iohyve create testvm 512M && iohyve getall testvm` would suffice.

**Comment by b4** [comment]
root@amethyst:~ # iohyve create testvm 512M && iohyve getall testvm
Creating testvm...
Getting testvm iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm4
cpu            1
description    Wed Jul 13 20:37:03 CDT 2016
loader         bhyveload
name           testvm
os             default
persist        1
ram            256M
size           512M
tap            tap4
template       NO
vnc            NO
vnc_h          600
vnc_ip         127.0.0.1
vnc_tablet     NO
vnc_w          800
vnc_wait       NO
root@amethyst:~ # iohyve list
Guest              VMM?  Running  rcboot?  Description
cheshire.gewt.net  YES   YES      NO       Fri Jan 22 14:20:56 EST 2016
mailer.gewt.net    YES   YES      NO       Fri Jan 22 14:42:20 EST 2016
ns1.gewt.net       NO    NO       NO       Fri Jan 22 14:02:15 EST 2016
pbx.gewt.net       NO    NO       NO       Sat Feb 27 16:51:07 CST 2016
testvm             NO    NO       NO       Wed Jul 13 20:37:03 CDT 2016

Looks like it was "using very old version to create the VM" issue

**Comment by pr1ntf** [comment]
Rad :sunglasses: 

I'll close out the issue.
