### ISSUE TITLE
Can't change number of vCPU's

### ISSUE THREAD

**Issue by pobkac** [pr1ntf/iohyve#199]
[iohyveTesting20160715 - Copy.txt](https://github.com/pr1ntf/iohyve/files/367094/iohyveTesting20160715.-.Copy.txt)
Hello, I am having an issue where I can not increase the number of virtual cpu cores from 2

I have tried 2 fresh installs of win10.
In creating the VM win10b I forgot to destroy the vmm in between restarts.  VM win10c was created destroying the VM in between restarts.

For both VM's changing the number of vcpu in iohyve did not change the number of cores reported by win10.

Uefi firmware is as downloaded 
`fetch https://people.freebsd.org/~grehan/bhyve_uefi/BHYVE_UEFI_20160526.fd`

I have a ssh log for the installs, I just can't upload it at the moment.  I'll try to upload it again later.  Is there any other information that you need?

Thanks
Brendan
edited formatting

**Comment by pr1ntf** [comment]
This is looking like an issue with Windows, not iohyve, or possibly a problem with your hardware. 

Every VM I am using is reporting the correct number of CPUs. I have not tried on any Windows guests yet. 

I will try to reproduce in the near future. 

Also, try to take a look at the GitHub Markdown, it would help out greatly, especially the code block [section](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting).

**Comment by pr1ntf** [comment]
This is indeed an issue with Windows 10. 
Booting a Windows 10 instance via UEFI with more than 2 CPUs shows only 2 CPUs. 
Booting a FreeBSD instance via UEFI with more than 2 CPUs shows the correct amount.

**Comment by pr1ntf** [comment]
Checking on the internet, this is a common issue. You may want to do some googling.
