### ISSUE TITLE
Cannot start vm after adding a second disk

### ISSUE THREAD

**Issue by plexorab** [pr1ntf/iohyve#203]
After adding a second disk with:

**iohyve add centos01 64G**

i get the following when starting the vm:

root@plexor12:~ # GRUB Process does not run in background....
If your terminal appears to be hanging, check iohyve console centos01 in second terminal to complete GRUB process...
_printf: missing format character_

.. and the vm is left at the grub-prompt.

**iohyve disks centos01** reports the added disk correctly.

---

root@plexor12:~ # iohyve version
iohyve v0.7.6 2016/06/12 Rideau Street Sinkhole Edition

root@plexor12:~ # iohyve getall centos01
Getting centos01 iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm2
cpu            4
description    Tue_Aug__2_22:42:43_CEST_2016
install        no
loader         grub-bhyve
name           centos01
os             centos7
pcidev:1       ahci-hd,/dev/zvol/zroot/iohyve/centos01/disk1
persist        1
ram            4096M
size           16G
tap            tap2
template       NO
vnc            YES
vnc_h          1050
vnc_ip         192.168.1.24
vnc_tablet     NO
vnc_w          1400
vnc_wait       NO

---

The error occur at line 354 in /usr/local/lib/iohyve/ioh-guest.

/Jimmy Jonsson

**Comment by pr1ntf** [comment]
Before we get started, can you please provide the output of `iohyve version` and `iohyve getall centos01`?

You can take a look at [GitHub Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) to help with pasting into this issue.

**Comment by pr1ntf** [comment]
My apologies, GitHub does not notify when a post has been edited, so I have not seen your changes until now. I'll try to replicate this issue.

**Comment by pr1ntf** [comment]
Adding the disk was done after a complete install, correct?

**Comment by houst0n** [comment]
I have this issue also, here is some more info:

```
FreeBSD hunter 10.3-RELEASE-p7 FreeBSD 10.3-RELEASE-p7 #0 r305290: Fri Sep  220:07:27 BST 2016     root@hunter:/usr/obj/usr/src/sys/ANTICHRIST  amd64

iohyve-0.7.6_1
```

Here's a VM with one disk:

```
root@hunter:~ # iohyve getall gfs1
Getting gfs1 iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm2
cpu            2
description    Fri__2_Sep_2016_21:36:16_BST
install        no
loader         grub-bhyve
name           gfs1
net            ue0
os             debian
persist        1
ram            2048
size           20G
tap            tap2
template       YES
vnc            NO
vnc_h          600
vnc_ip         127.0.0.1
vnc_tablet     NO
vnc_w          800
vnc_wait       NO
root@hunter:~ #
```

It boots fine:

```
root@hunter:~ # iohyve start gfs1
Starting gfs1... (Takes 15 seconds for FreeBSD guests)
root@hunter:~ # GRUB Process does not run in background....
If your terminal appears to be hanging, check iohyve console gfs1 in second terminal to complete GRUB process...

root@hunter:~ # iohyve console gfs1
Starting console on gfs1...
~~. to escape console [uses cu(1) for console]
Connected

Debian GNU/Linux 8 rename_me ttyS0
gfs1 login: 
[EOT]
```

If I shutdown the VM, add a new disk and start it -- this happens:

```
root@hunter:~ # iohyve stop gfs1
Stopping gfs1...

root@hunter:~ # iohyve destroy gfs1
Destroying gfs1...
VM:ioh-gfs1 is not created.
VM:ioh-gfs1 is not created.

root@hunter:~ # iohyve list
Guest  VMM?  Running  rcboot?  Description
dt     NO    NO       NO       Fri  2 Sep 2016 18:06:20 BST
gfs1   NO    NO       NO       Fri__2_Sep_2016_21:36:16_BST
gt     NO    NO       NO       Fri__2_Sep_2016_18:21:20_BST

root@hunter:~ # iohyve add gfs1 20G
Creating new zvol for gfs1...

root@hunter:~ # iohyve start gfs1
Starting gfs1... (Takes 15 seconds for FreeBSD guests)
root@hunter:~ # GRUB Process does not run in background....
If your terminal appears to be hanging, check iohyve console gfs1 in second terminal to complete GRUB process...
printf: missing format character

root@hunter:~ # iohyve console gfs1
Starting console on gfs1...
~~. to escape console [uses cu(1) for console]
Connected
grub> ls
(host)
```

Also note,  removing the disk reverts the issue:

```
root@hunter:/iohyve/gfs1 # iohyve remove gfs1 disk1
Are you sure you want to remove disk1 from gfs1 [Y/N]? y
root@hunter:/iohyve/gfs1 # iohyve start gfs1
Starting gfs1... (Takes 15 seconds for FreeBSD guests)
root@hunter:/iohyve/gfs1 # GRUB Process does not run in background....
If your terminal appears to be hanging, check iohyve console gfs1 in second terminal to complete GRUB process...

root@hunter:/iohyve/gfs1 # iohyve console gfs1
Starting console on gfs1...
~~. to escape console [uses cu(1) for console]
Connected

Debian GNU/Linux 8 rename_me ttyS0

gfs1 login: ~
[EOT]
```

Running it with -x shows this:

```
+ echo 'GRUB Process does not run in background....'
GRUB Process does not run in background....
+ echo 'If your terminal appears to be hanging, check iohyve console gfs1 in second terminal to complete GRUB process...'
If your terminal appears to be hanging, check iohyve console gfs1 in second terminal to complete GRUB process...
+ [ no = yes ]
+ [ no = no ]
+ [ debian = openbsd59 ]
+ [ debian = openbsd58 ]
+ [ debian = openbsd57 ]
+ [ debian = netbsd ]
+ [ debian = debian ]
+ printf '\(hd0\)\ /dev/zvol/zroot/iohyve/gfs1/disk0' 'zroot/iohyve/gfs1/disk1\n'
printf: missing format character
+ printf '\(cd0\)\ /dev/zvol/zroot/iohyve/gfs1/disk0\n'
+ grub-bhyve -m /iohyve/gfs1/device.map -r hd0,msdos1 -c /dev/nmdm2A -M 2048 ioh-gfs1
```

And the map is a bit borked after that:

```
root@hunter:~ # cat /iohyve/gfs1/device.map
(hd0) /dev/zvol/zroot/iohyve/gfs1/disk0(cd0) /dev/zvol/zroot/iohyve/gfs1/disk0
```

**Comment by houst0n** [comment]
PR here:

https://github.com/pr1ntf/iohyve/pull/204

**Comment by pr1ntf** [comment]
PR #204 has been merged. If you are still having these problems @plexorab please try pulling down the latest GitGub with @houst0n 's fixes. 

If problems persist, please feel free to comment in this issue and I'll reopen the issue. 

Thank you.
