### ISSUE TITLE
Update OpenBSD 5.9 to 6.0 (boot guest on iso)

### ISSUE THREAD

**Issue by src386** [pr1ntf/iohyve#206]
Hello,

I have a VM running OpenBSD 5.9.
I'm trying to update to OpenBSD 6.0 using the iso : 

```
iohyve stop vm-ssl
iohyve fetch http://ftp.fr.openbsd.org/pub/OpenBSD/6.0/amd64/install60.iso
iohyve install vm-ssl install60.iso
```

But I just get a minimal GRUB Bash...
I think I'm just unable to boot on ISO when the guest is already installed.
Or maybe OpenBSD6.0 isn't supported yet ?

```
[root@freenas] ~# iohyve getall vm-ssl
Getting vm-ssl iohyve properties...
bargs          -A_-H_-P
boot           1
con            nmdm0
cpu            1
description    Wed Jul 27 15:42:17 CEST 2016
install        yes
loader         grub-bhyve
name           vm-ssl
os             openbsd
persist        1
ram            256M
rcboot         yes
size           10G
tap            tap0
```

**Comment by src386** [comment]
Okay I found a workaround.
In the openbsd VM, download **bsd.rd** (6.0) to the root.
Then, on the guest zfs dataset, edit grub.cfg and modify to bsd.rd.
Set the vm to os=custom, then boot, and perform the install.
Set grub.cfg back to bsd and boot.
Profit.

**Comment by pr1ntf** [comment]
When using OpenBSD and `iohyve` you must specify the version in your `os` property. 
If you want to try out OpenBSD 6.0, then you can try something like `iohyve set vm-ssl os=openbsd60`
If you wanted to go back to 5.9, then something like `iohyve set vm-ssl os=openbsd59`

Let me know if this helps any!

**Comment by src386** [comment]
`os=openbsd60` is not working, but I'm not sure I have the latest version of iohyve, I'm using the one on FreeNAS. How can I list all supported `os=` ? Is there a command like iohyve list property os ?

**Comment by pr1ntf** [comment]
Ah, yes, I should have specified, the version on GitHub is the only version that will support 6.0. 

For now, following [this](https://github.com/pr1ntf/iohyve#use-your-own-custom-grubcfg-and-devicemap-files) little guide should get you going, as you probably already read. 

There is no way to check what iohyve os's you can use without looking at the "source" (`ioh-guest`) currently.
