### ISSUE TITLE
Unable to correctly boot Windows, works with bhyve directly

### ISSUE THREAD

**Issue by Pricetx** [pr1ntf/iohyve#208]
I'm having issues getting a Windows installer ISO to boot with iohyve using UEFI. I'll start by showing a raw bhyve command which I can run which does successfully load the installer, as hopefully it'll narrow down the problem.

    truncate -s 10G uefi-test.img

    sudo bhyve -c 2 -m 2G -w -H \
        -s 0,hostbridge \
        -s 3,ahci-cd,../iso/Win10_1511_English_x64.iso \
        -s 4,ahci-hd,uefi-test.img \
        -s 5,virtio-net,tap0 \
        -s 29,fbuf,tcp=0.0.0.0:5900,w=800,h=600,wait \
        -s 30,xhci,tablet \
        -s 31,lpc -l com1,stdio \
        -l bootrom,/usr/local/share/uefi-firmware/BHYVE_UEFI.fd \
        uefi-test

This is the procedure I followed to create a comparable VM using iohyve:

    sudo iohyve create wintest 10G zroot
    sudo iohyve set wintest loader=uefi ram=2G cpu=2 vnc=YES vnc_ip=0.0.0.0 vnc_port=5900 vnc_wait=YES vnc_tablet=YES bargs="-H -w"
    sudo iohyve install wintest Win10_1511_English_x64.iso

This gave the error `You must set a firmware file property to use UEFI...` which from looking through the source of iohyve I fixed by doing the following:

    sudo iohyve cpfw /usr/local/share/uefi-firmware/BHYVE_UEFI.fd
    sudo iohyve set wintest fw=BHYVE_UEFI.fd

    sudo iohyve install wintest Win10_1511_English_x64.iso

At this point, the VM launched, but the Windows instance itself has gone to an error screen rather than booting the installer like when I use bhyve directly. Here is a screenshot of the error screen: http://i.imgur.com/ScYRiqe.png

Here is the output of iohyve getall wintest:

    Getting wintest iohyve properties...
    bargs          -H_-w
    boot           0
    con            nmdm0
    cpu            2
    description    Tue  8 Nov 2016 13:08:25 UTC
    fw             BHYVE_UEFI.fd
    loader         uefi
    name           wintest
    os             default
    persist        1
    ram            2G
    size           10G
    tap            tap0
    vnc            YES
    vnc_h          600
    vnc_ip         0.0.0.0
    vnc_port       5900
    vnc_tablet     YES
    vnc_w          800
    vnc_wait       YES 

Do you have any ideas as to what is causing my issue?

**Comment by pr1ntf** [comment]
Before we begin, did you copy the ISO file over to `iohyve` using the `iohyve cpiso` function?

**Comment by Pricetx** [comment]
Sorry, yes, I managed to miss that from my original post. I used `iohyve cpiso Win10_1511_English_x64.iso` to import the ISO into iohyve

**Comment by pr1ntf** [comment]
I see you have specified the install to be on a different pool than normal, can you also post the output of `zfs list`? `iohyve` may not be finding the correct data set.

Also note that 10G is smaller than the minimum requirements for [Windows 10](https://www.microsoft.com/en-us/windows/windows-10-specifications). (20 GB for 64-bit OS)

**Comment by Pricetx** [comment]
Ah, yes. I had forgotten that it was not normal to specify the pool during the creation command. The reason I had done this was because when I omitted the pool name I got the following:

```
sudo iohyve create wintest 20G
Creating wintest...
too many arguments
usage:
    create [-pu] [-o property=value] ... <filesystem>
    create [-ps] [-b blocksize] [-o property=value] ... -V <size> <volume>

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
too many arguments
usage:
    create [-pu] [-o property=value] ... <filesystem>
    create [-ps] [-b blocksize] [-o property=value] ... -V <size> <volume>

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
```

It looks like it passes something incorrect to `zfs create`.

Here's the output of zfs list, this actually look okay:

EDIT: I had pasted an incorrect copy of zfs list previously, the updated one includes the missing filesystems

```
NAME                                              USED  AVAIL  REFER  MOUNTPOINT
zroot                                            21.3G  1.74T    96K  /zroot
zroot/ROOT                                       1.41G  1.74T    96K  none
zroot/ROOT/default                               1.41G  1.74T  1.41G  /
zroot/iohyve                                     11.4G  1.74T    96K  /iohyve
zroot/iohyve/Firmware                             972K  1.74T    96K  /iohyve/Firmware
zroot/iohyve/Firmware/BHYVE_UEFI.fd               876K  1.74T   876K  /iohyve/Firmware/BHYVE_UEFI.fd
zroot/iohyve/ISO                                 1.09G  1.74T    96K  /iohyve/ISO
zroot/iohyve/ISO/Win10_1511_English_x64.iso       873M  1.74T   873M  /iohyve/ISO/Win10_1511_English_x64.iso
zroot/iohyve/ISO/debian-8.6.0-amd64-netinst.iso   239M  1.74T   239M  /iohyve/ISO/debian-8.6.0-amd64-netinst.iso
zroot/iohyve/wintest                             10.3G  1.74T    96K  /iohyve/wintest
zroot/iohyve/wintest/disk0                       10.3G  1.75T    64K  -
zroot/tmp                                         112K  1.74T   112K  /tmp
zroot/usr                                        8.47G  1.74T    96K  /usr
zroot/usr/home                                   8.47G  1.74T  8.47G  /usr/home
zroot/usr/ports                                    96K  1.74T    96K  /usr/ports
zroot/usr/src                                      96K  1.74T    96K  /usr/src
zroot/var                                         748K  1.74T    96K  /var
zroot/var/audit                                    96K  1.74T    96K  /var/audit
zroot/var/crash                                    96K  1.74T    96K  /var/crash
zroot/var/log                                     256K  1.74T   256K  /var/log
zroot/var/mail                                    108K  1.74T   108K  /var/mail
zroot/var/tmp                                      96K  1.74T    96K  /var/tmp
```

Also, thanks for pointing out the minimum storage requirement. I was just using that as a placeholder figure while I get everything working. I will set a much higher figure when I actually get around to installing the OS.

EDIT: I had pasted an incorrect copy of zfs list previously, the updated one includes the missing filesystems

**Comment by pr1ntf** [comment]
Your guest dataset is not in that list. 
You should see something like `zroot/iohyve/wintest`.

**Comment by Pricetx** [comment]
Sorry, you might want to refresh the issue page. I initially pasted the output of zfs list after I destroyed the VM to see what happened if I ran `iohyve create` without specifying a pool. I have updated the post with the correct output of zfs list, which does include the guest dataset.

**Comment by pr1ntf** [comment]
I cannot reproduce this at all. 

Can you proved the debugging output? 

You can try running something like `sh -x /usr/local/sbin/iohyve install wintest windows.iso`

**Comment by Pricetx** [comment]
From a cursory glance I can't see anything out of the ordinary, but obviously you have more experience in these matters. Output is below:

```
sudo sh -x /usr/local/sbin/iohyve install wintest Win10_1511_English_x64.iso
+ PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/pricetx/bin:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
+ grep POPCNT /var/run/dmesg.boot
+ [ -n '  Features2=0x1d9ae3bf<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,EST,TM2,SSSE3,CX16,xTPR,PDCM,PCID,SSE4.1,SSE4.2,POPCNT,TSCDLT,XSAVE,OSXSAVE,AVX>' ]
+ grep CPU: /var/run/dmesg.boot
+ grep Intel
+ [ -n 'CPU: Intel(R) Core(TM) i3-2130 CPU @ 3.40GHz (3392.36-MHz K8-class CPU)' ]
+ grep VT-x: /var/run/dmesg.boot
+ grep UG
+ [ -z '  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID' ]
+ [ -e ./lib/ioh-cmd ]
+ [ -e /usr/local/lib/iohyve ]
+ LIB=/usr/local/lib/iohyve
+ . /etc/rc.subr
+ : 1832
+ export RC_PID
+ [ -z '' ]
+ _rc_subr_loaded=YES
+ SYSCTL=/sbin/sysctl
+ SYSCTL_N='/sbin/sysctl -n'
+ SYSCTL_W=/sbin/sysctl
+ PROTECT=/usr/bin/protect
+ ID=/usr/bin/id
+ IDCMD='if [ -x /usr/bin/id ]; then /usr/bin/id -un; fi'
+ PS='/bin/ps -ww'
+ /bin/ps -ww -p 1832 -o 'jid='
+ JID=0
+ _rc_namevarlist='program chroot chdir env flags fib nice user group groups prepend'
+ _rc_subr_loaded=:
+ . /usr/local/lib/iohyve/ioh-cmd
+ . /usr/local/lib/iohyve/ioh-setup
+ . /usr/local/lib/iohyve/ioh-zfs
+ . /usr/local/lib/iohyve/ioh-console
+ . /usr/local/lib/iohyve/ioh-iso
+ . /usr/local/lib/iohyve/ioh-firmware
+ . /usr/local/lib/iohyve/ioh-guest
+ . /usr/local/lib/iohyve/ioh-disk
+ . /usr/local/lib/iohyve/ioh-tap
+ [ -z install ]
+ __root_req_cmd install
+ return 0
+ whoami
+ [ root '!=' root ]
+ __parse_cmd install wintest Win10_1511_English_x64.iso
+ [ 3 -gt 0 ]
+ __guest_install install wintest Win10_1511_English_x64.iso
+ local 'name=wintest'
+ local 'iso=Win10_1511_English_x64.iso'
+ [ -z Win10_1511_English_x64.iso ]
+ __guest_exist wintest
+ zfs get -H -s local -o value iohyve:name
+ grep '^wintest$'
+ zfs get -H -s local -o name,value -t filesystem iohyve:name
+ printf '\t'
+ grep $'\twintest$'
+ cut -f1
+ local 'dataset=zroot/iohyve/wintest'
+ zfs get -H -o value mountpoint zroot/iohyve/wintest
+ local 'mountpoint=/iohyve/wintest'
+ zfs get -H -o value iohyve:loader zroot/iohyve/wintest
+ local 'loader=uefi'
+ [ uefi '=' uefi ]
+ __guest_uefi wintest Win10_1511_English_x64.iso
+ local 'name=wintest'
+ local 'media=Win10_1511_English_x64.iso'
+ [ -z wintest ]
+ __guest_exist wintest
+ zfs get -H -s local -o value iohyve:name
+ grep '^wintest$'
+ zfs get -H -s local -o name,value -t filesystem iohyve:name
+ printf '\t'
+ grep $'\twintest$'
+ cut -f1
+ local 'dataset=zroot/iohyve/wintest'
+ zfs get -H -o value iohyve:ram zroot/iohyve/wintest
+ local 'ram=2G'
+ zfs get -H -o value iohyve:con zroot/iohyve/wintest
+ local 'con=nmdm0'
+ zfs get -H -o value iohyve:cpu zroot/iohyve/wintest
+ local 'cpu=2'
+ zfs get -H -o value iohyve:fw zroot/iohyve/wintest
+ local 'fw=BHYVE_UEFI.fd'
+ zfs get -H -o value iohyve:tap zroot/iohyve/wintest
+ local 'tap=tap0'
+ zfs get -H -o value iohyve:bargs zroot/iohyve/wintest
+ sed -e 's/_/ /g'
+ local 'bargs=-H -w'
+ zfs get -H -o value iohyve:vnc zroot/iohyve/wintest
+ local 'vnc=YES'
+ zfs get -H -o value iohyve:vnc_ip zroot/iohyve/wintest
+ local 'vnc_ip=0.0.0.0'
+ zfs get -H -o value iohyve:vnc_port zroot/iohyve/wintest
+ local 'vnc_port=5900'
+ zfs get -H -o value iohyve:vnc_w zroot/iohyve/wintest
+ local 'vnc_w=800'
+ zfs get -H -o value iohyve:vnc_h zroot/iohyve/wintest
+ local 'vnc_h=600'
+ zfs get -H -o value iohyve:vnc_wait zroot/iohyve/wintest
+ local 'vnc_wait=YES'
+ zfs get -H -o value iohyve:vnc_tablet zroot/iohyve/wintest
+ local 'vnc_tablet=YES'
+ zfs list -H -t volume -o name
+ grep iohyve/wintest
+ cut -d / -f1
+ local 'pool=zroot'
+ ifconfig -l
+ tr ' ' '\n'
+ grep -F -w tap0
+ local 'tapif=tap0'
+ [ -z tap0 ]
+ [ BHYVE_UEFI.fd '=' - ]
+ zfs get -H -o value mountpoint zroot/iohyve/wintest
+ local 'mountpoint=/iohyve/wintest'
+ [ -d /iohyve/wintest ]
+ pgrep -fx 'bhyve: ioh-wintest'
+ local 'running='
+ [ -z ]
+ [ YES '=' YES ]
+ [ YES '=' YES ]
+ vncline='-s 11,fbuf,tcp=0.0.0.0:5900,w=800,h=600,wait'
+ [ YES '=' YES ]
+ tabletline='-s 12,xhci,tablet'
+ exit 0
+ bhyve -c 2 -H -w -m 2G -s 0,hostbridge -s 3,ahci-cd,/iohyve/ISO/Win10_1511_English_x64.iso/Win10_1511_English_x64.iso -s '4,ahci-hd,/dev/zvol/zroot/iohyve/wintest/disk0,sectorsize=512' -s 10,virtio-net,tap0 -s '11,fbuf,tcp=0.0.0.0:5900,w=800,h=600,wait' -s 12,xhci,tablet -s 31,lpc -l com1,/dev/nmdm0A -l bootrom,/iohyve/Firmware/BHYVE_UEFI.fd/BHYVE_UEFI.fd ioh-wintest

pricetx@wright:/home/pricetx>fbuf frame buffer base: 0x882800000 [sz 16777216]
```

Note that I did make sure that it was definitely still giving that Windows error, and it is. I am also still able to directly create windows VMs using that bhyve command I originally posted.

**Comment by pr1ntf** [comment]
Try that original bhyve command but with the disk as `/dev/zvol/zroot/iohyve/wintest/disk0,sectorsize=512` the hardcoded sector size might be causing an issue on your machine. 

`-s 4,ahci-hd,/dev/zvol/zroot/iohyve/wintest/disk0,sectorsize=512 \`

**Comment by Pricetx** [comment]
I ran two commands:
1) As you suggested, the original bhyve command with the iohyve disk line
2) The iohyve command with the original bhyve disk line

I was able to successfully boot the Windows installer with 1), but 2) still failed to boot, even using the .img file rather than the zvol.

**Comment by Pricetx** [comment]
I have now found the fix for this. When I replaced the ahci-cd line, it started working. This led me to performing an `rmiso` followed by a `cpiso` for the .iso file. Once I did this it started behaving correctly. I can only assume the original `cpiso` command must have been interrupted or something. I don't believe there's any issue with iohyve itself.

**Comment by pr1ntf** [comment]
Quite the fun rabbit hole this morning. ☕️  Glad you got it sorted out. 😀
