### ISSUE TITLE
iohyve cpiso cannot handle file names with spaces

### ISSUE THREAD

**Issue by jmdavis** [pr1ntf/iohyve#209]
I ran this command:

    sudo iohyve cpiso /zdata/ISOs/Windows\ 7\ SP1\ Ultimate\ x64\ en-us\ Nov2014\ Pre-Activated@Only\ By\ THE\ RAIN-=TEAM\ OS=-\{HKRG\}/Windows\ 7\ SP1\ Ultimate\ x64\ en-us\ Nov2014.iso

and got this error

    [: /zdata/ISOs/Windows: unexpected operator
    Copying Windows
    7
    SP1
    Ultimate
    x64
    en-us
    Nov2014
    Pre-Activated@Only
    By
    THE
    RAIN-=TEAM
    Windows
    7
    SP1
    Ultimate
    x64
    en-us
    Nov2014.iso from /zdata/ISOs/Windows 7 SP1 Ultimate x64 en-us Nov2014 Pre-Activated@Only By THE RAIN-=TEAM OS=-{HKRG}/Windows 7 SP1 Ultimate x64 en-us Nov2014.iso...
    too many arguments
    usage:
            create [-pu] [-o property=value] ... <filesystem>
            create [-ps] [-b blocksize] [-o property=value] ... -V <size> <volume>

    For the property list, run: zfs set|get

    For the delegated permission list, run: zfs allow|unallow
    cp: Nov2014.iso is not a directory

I guess that that's what I get for trying to figure out how to get everything set up properly with a pirated version of Windows before doing it for real with a properly licensed one. ;)

In all seriousness, it's clear that `iohyve cpiso` is not escaping the file name properly. At minimum, it doesn't handle spaces correctly, and I'd guess that characters that the shell treats specially would have problems as well. It wouldn't surprise me if other iohyve commands which take file names  (e.g. `iohyve cpfw`) have similar problems, but I haven't tested them.

**Comment by pr1ntf** [comment]
This is a known issue in the way `iohyve` handles just about everything. 

I really don't want to say something like "it's UNIX you shouldn't have file names with spaces anyway" but that's totally bad. 

There is work to clean this kind of stuff up. Until now, I suggest something like `mv "My Backdoored Copy Of Windows Uber Ultimate Cracked by +++====CYB3R_TEAM-420===+++.ISO" windows7.iso` then use `iohyve cpiso windows7.iso` ;)

**Comment by pr1ntf** [comment]
Closing this issue as it is now added to our [roadmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0).
