### ISSUE TITLE
Altering properties of a guest breaks the boot

### ISSUE THREAD

**Issue by SteffanA** [pr1ntf/iohyve#211]
First off, this is on FreeNAS which is still on V0.7.5, so these issues may have been fixed in the current release.
I was having issues creating a new guest (which I might make a new issue thread for later), so I decided to alter one I had left unused.  I ran the following commands...

`Guest    VMM?  Running  rcboot?  Description
cserver  NO    NO       NO       Fri Apr 22 21:41:25 PDT 2016
pihole   YES   YES      YES      Sat Oct  1 14:10:56 PDT 2016
vsearch  YES   YES      YES      Thu Apr 21 13:39:12 PDT 2016
[s@freenas] ~% sudo iohyve getall cserver
Getting cserver iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm1
cpu            1
description    Fri Apr 22 21:41:25 PDT 2016
install        no
loader         grub-bhyve
name           cserver
net            igb2
os             debian
os-debian      os-debian
persist        1
ram            512M
size           4G
tap            tap1
[s@freenas] ~% sudo iohyve set cserver ram=2G
Setting cserver ram=2G...
[s@freenas] ~% sudo iohyve getall cserver
Getting cserver iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm1
cpu            1
description    Fri Apr 22 21:41:25 PDT 2016
install        no
loader         grub-bhyve
name           cserver
net            igb2
os             debian
os-debian      os-debian
persist        1
ram            2G
size           4G
tap            tap1
[s@freenas] ~% sudo iohyve set cserver cpu=6
Setting cserver cpu=6...
[s@freenas] ~% sudo iohyve getall cserver
Getting cserver iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm1
cpu            6
description    Fri Apr 22 21:41:25 PDT 2016
install        no
loader         grub-bhyve
name           cserver
net            igb2
os             debian
os-debian      os-debian
persist        1
ram            2G
size           4G
tap            tap1
[s@freenas] ~% sudo iohyve add cserver 20G morespace
Creating new zvol for cserver...
cannot open 'morespace': no such pool
[s@freenas] ~% sudo iohyve getall cserver
Getting cserver iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm1
cpu            6
description    Fri Apr 22 21:41:25 PDT 2016
install        no
loader         grub-bhyve
name           cserver
net            igb2
os             debian
os-debian      os-debian
pcidev:1       ahci-hd,/dev/zvol/morespace/iohyve/cserver/disk1
persist        1
ram            2G
size           4G
tap            tap1
[s@freenas] ~% sudo iohyve add cserver 20G morespace
Creating new zvol for cserver...
cannot open 'morespace': no such pool
[s@freenas] ~% sudo iohyve getall cserver
Getting cserver iohyve properties...
bargs          -A_-H_-P
boot           0
con            nmdm1
cpu            6
description    Fri Apr 22 21:41:25 PDT 2016
install        no
loader         grub-bhyve
name           cserver
net            igb2
os             debian
os-debian      os-debian
pcidev:1       ahci-hd,/dev/zvol/morespace/iohyve/cserver/disk1
pcidev:2       ahci-hd,/dev/zvol/morespace/iohyve/cserver/disk1
persist        1
ram            2G
size           4G
tap            tap1
[s@freenas] ~% sudo iohyve start cserver
Starting cserver... (Takes 15 seconds for FreeBSD guests)
[s@freenas] ~% Could not open backing file: No such file or directory

[s@freenas] ~% sudo iohyve start cserver
Starting cserver... (Takes 15 seconds for FreeBSD guests)
[s@freenas] ~% Could not open backing file: No such file or directory
[s@freenas] ~% sudo iohyve list
Guest    VMM?  Running  rcboot?  Description
cserver  NO    NO       NO       Fri Apr 22 21:41:25 PDT 2016
pihole   YES   YES      YES      Sat Oct  1 14:10:56 PDT 2016
vsearch  YES   YES      YES      Thu Apr 21 13:39:12 PDT 2016
[s@freenas] ~% sudo iohyve destroy cserver
Destroying cserver...
VM:ioh-cserver is not created.
VM:ioh-cserver is not created.
[s@freenas] ~% sudo iohyve start cserver
Starting cserver... (Takes 15 seconds for FreeBSD guests)
[s@freenas] ~% Could not open backing file: No such file or directory
sudo iohyve start cserver
Starting cserver... (Takes 15 seconds for FreeBSD guests)
[s@freenas] ~% Could not open backing file: No such file or directory`

As you can see, after running said commands, the guest was not able to boot.  When console-ing into the guest, on the start command, it would boot into GRUB with normal Ubuntu boot options; however, none of these options work - selecting any of them leads to a blank console and the "Could not open backing file" message appears on the terminal of my other connection instance.

My trying to add a new dataspace twice with the same name might be an issue.... Additionally, I'm not sure how that command is supposed to go when it works completely, but my file structure doesn't appear to have changed at all, and the device.map for cserver looks like this:
`(hd0) /dev/zvol/SSD_Storage/iohyve/cserver/disk0
(cd0) /dev/zvol/SSD_Storage/iohyve/cserver/disk0`

Which mirrors my working guests without any additional storage.

Side note, thanks so much for creating this tool, it's been super helpful.  Also, uncertain if this is more bug or troubleshooting... if you feel it's the latter I can remove this issue request.  Additionally, I wasn't quite sure if this was the same issue as #203 or not - it seems similar but at the same time, different errors.

**Comment by pr1ntf** [comment]
That is indeed a pretty old version. There have been numerous fixes to GRUB support since then. 

I've been trying to track down a concrete way of updating `iohyve` in FreeNAS via GitHub. They never seem to update the port. I don't run FreeNAS on anything so this is hard to duplicate. 

Can you tell me what version of FreeNAS you are on?

**Comment by SteffanA** [comment]
I'm currently on the latest stable version, FreeNAS-9.10.1-U4. I know there were talks in the forums about trying to upgrade iohyve without freenas devs having to push through the updates, but I don't think anything came of it. I also saw a post saying they weren't sure if it was going to make it into 10.0, but I'll try to figure out where the best place is to make a feature request, because I have really enjoyed using iohyve up to this point.

**Comment by pr1ntf** [comment]
I think you poked the right people. 
I just received word that `iohyve` in FreeNAS ports is now at `0.7.7` for now. 🎉 

I understood it as `iohyve` was a "shim" until the awesome folks at iX had their manager ready to go for FreeNAS 10. 

I'm glad you like the software, it's not going anywhere anytime soon. The kind words do mean a lot!

Go ahead and update, and if you still have the problem, we can reopen this ticket.

**Comment by sysfu** [comment]
I simply filed a [bug report](https://bugs.freenas.org/issues/19098) requesting the update and Kris M. took care of it same day.

iohyve does indeed appear to be an 'experimental' bone thrown to bhyve enthusiasts until the FreeNAS 10x VM management interface is ready for primetime. Read [this freenas forum thread](forums.freenas.org/index.php?threads/jails-plugins-and-containers-vms-in-10.43830/) if you want to dig into the discussion about why.

I would prefer to see a command line interface (such as that provided by iohyve) in addition to the GUI interface, but alas that is probably not in the cards.

I do see a 'bhyvectl' utility included with FreeNAS 10 however documentation and functionality suffers in comparison to iohyve IMO.

**Comment by pr1ntf** [comment]
From what I understand, there is going to be a better jail/bhyve management from their webui. 
Of course even if you would want to keep with iohyve, vm-bhyve, etc.... it probably wouldn't play nice with whatever tool they built in. 

I think you are referring to the bhyve utility [bhyvectl(8)](https://www.freebsd.org/cgi/man.cgi?query=bhyvectl&apropos=0&sektion=8&manpath=FreeBSD+11.0-RELEASE&arch=default&format=html). I might be wrong though.

**Comment by sysfu** [comment]
Yes I was referring to the bhyvectl utility. Most of the FreeNAS devices I administer are remote so I like to do everything via SSH and the terminal when possible. A fully featured bhyve VM management command line utility such as iohyve is very useful on those scenarios.

**Comment by SteffanA** [comment]
Thanks @sysfu for writing the request; I had got busy and didn't get around to it, good to see someone else did it for me!  Once the folks at FreeNAS push out a new stable version, I'll update and see if my issue is fixed.
