### ISSUE TITLE
Windows guest (UEFI) is not restarted after guest reboot

### ISSUE THREAD

**Issue by abishai** [pr1ntf/iohyve#212]
/subj/
```
iohyve v0.7.7 2016/11/10 I Think I'll Go for a Walk Edition
```
```
bargs          -A_-H_-P
boot           1
con            nmdm2
cpu            1
description    Wed Nov 16 10:49:04 MSK 2016
fw             bhyve-uefi.fd
loader         uefi
name           quik-dev
os             default
persist        2
ram            1G
size           40G
tap            tap2
vnc            NO
vnc_h          768
vnc_ip         10.0.1.2
vnc_port       5900
vnc_tablet     NO
vnc_w          1024
vnc_wait       YES
```
Windows Server 2008 R2 (and Windows 7) guest ignores persist settings for both reboot and shutdown.

**Comment by pr1ntf** [comment]
This is to be expected right now. 
As mentioned previously, UEFI booting in `iohyve` is still experimental. (Thus why it is not documented)

You can only attach one disk, and one network tap. Do not expect automatic reboots or UEFI guests to start at boot time. 

Again, we are working on better UEFI support in future releases, outlined [here](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#08-goals).
