### ISSUE TITLE
Support bhyve's -u flag

### ISSUE THREAD

**Issue by jmdavis** [pr1ntf/iohyve#216]
For some reason, bhyve defaults to having the system clock be in localtime instead of UTC (which works well for Windows but not so well for *nix OSes). It does, however, have the -u flag to tell it to put the system clock for the VM in UTC. So, it would be nice if iohyve had a way to set that, similar to how it has other zfs properties such as `iohyve:vnc` or `iohyve:size`. It could have `iohyve:utc` which could be set to `YES` or `NO` like the other true/false zfs properties are done with iohyve.

**Comment by jmdavis** [comment]
https://github.com/pr1ntf/iohyve/pull/219

**Comment by pr1ntf** [comment]
Closing this issue to discuss in PR #219
