### ISSUE TITLE
Utilize achi-hd over virtio-blk for HDD emultion. 

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#22]
Utilize achi-hd over virtio-blk for HDD emultion. 
This could help with the use of root on ZFS builds (FreeBSD and TrueOS) and Linux LVM setups.

**Comment by pr1ntf** [comment]
Maybe add some zvol.

**Comment by pr1ntf** [comment]
I know @3add3287 had some great ideas about zvol used as block devices. I think using ahci-hd + zvol should be the default way to store block devices in iohyve moving forward. Virtio can be an option.

**Comment by pr1ntf** [comment]
Creating zvol fork from master
If anyone would like to contribute, please pull against zvol-support. :grinning:

**Comment by pr1ntf** [comment]
So far I have Root on ZFS working with at least 1024M of RAM. 
Working on UFS support. Seems to crash for me no matter ahci-hd or virtio-blk.

**Comment by pr1ntf** [comment]
I think UFS is being picky about block size. 
ahci-hd and virtio-blk give write errors.

**Comment by pr1ntf** [comment]
Fixed. 
Of course I found an Allan Jude ZFS email regarding the issue. 

```
zfs create -V 16G -o volmode=dev pool/iohyve/bhyvebutts/bhyvebutts0.img
```

Will be pushing this to zvol-support branch later today, unless anyone beats me. :wink:

**Comment by pr1ntf** [comment]
ahci-hd and zvol support now default as of v0.3.5
Commit 2ac78021934791d6ee9e7c88db3e63564d0c56ec

**Comment by lbschenkel** [comment]
I didn't understand the motivation for adopting ahci-cd over virtio-blk, since (on paper) the latter should have lower overhead. Reliability/stability? Something else?

**Comment by pr1ntf** [comment]
Digging back for this one. 

We made the choice to stick with `ahci-hd` because it was the HDD emulation that was written by the folks who wrote `bhyve` as I understand it. 

At the time, we wanted `iohyve` to only utilize one HDD emulation type as to make it simple for that point in the tool's growth. `ahci-hd` was working just fine for the operating systems that were supported at that `iohyve` version. 

No testing, no thoughts on overhead, just trying to make things simple. 

No one thus far has come around saying they can't virtualize a certain OS because they can't utilize `virtio-blk` in `iohyve` so it's stuck around.

**Comment by 3add3287** [comment]
There's no TRIM support in virtio-blk and it seems impossible to add with the way the virtio-blk API has been designed.

**Comment by lbschenkel** [comment]
Thanks for the clarification. Makes sense.
