### ISSUE TITLE
Question: iohyve second disk different dataset

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#225]
Hi,

How do you do with iohyve to add a second disk and point it out to a different dataset ?
I'm using Freenas but I can setup iohyve with one array of disk with a dataset but I don't know how to add a second vm to another dataset or add a second disk to the same VM to use another dataset from a different array of disk.

Thanks

**Comment by pr1ntf** [comment]
If you want to add a disk that lives on a separate pool than the boot disk, you can set up `iohyve` on the second pool with something like `iohyve setup pool=nameofsecondpool` and then follow the steps on adding a new disk, as detailed in the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L227).

**Comment by pr1ntf** [comment]
Closing this issue. Please feel free to respond to this ticket if my answer did not solve your problem. Thanks!
