### ISSUE TITLE
Viva la BSD

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#23]
Get 'iohyve start' support for OpenBSD and NetBSD guests.

**Comment by pr1ntf** [comment]
NetBSD guests can be manually loaded and booted as of right now. 
OpenBSD won't install out of the box quite yet.

**Comment by grehan-freebsd** [comment]
Any error messages with OpenBSD ? It should be able to install/boot fine.

**Comment by grehan-freebsd** [comment]
Here's a sample OpenBSD grub-bhyve install command line.

grub-bhyve -r cd0 -m obsd.map -M 2048 obsd57-amd64
kopenbsd -h com0  /5.7/amd64/bsd.rd
boot

To boot it post-install you have to specify the type of root device with the "-r" option e.g.

grub-bhyve -r hd0,openbsd1 -m obsd.map -M 2048 obsd57-amd64
kopenbsd -h com0 -r sd0a /bsd
boot

**Comment by pr1ntf** [comment]
OpenBSD guests can install correctly under the grub-support branch now. 
It does not work using:

```
iohyve start openbsdguest
```

You must manually run:

```
iohyve load openbsdguest
iohyve boot openbsdguest
```

**Comment by pr1ntf** [comment]
Reopening due to recent headaches with grub2-bhyve being resolved. :grinning: 

Also, attaching to the "grub2-bhyve" support milestone tag.

**Comment by pr1ntf** [comment]
@grehan-freebsd thank you so much for your help and for your work on grub2-bhyve.  iohyve now has OpenBSD support :grinning:
