### ISSUE TITLE
iohyve list, don't show deleted VMs

### ISSUE THREAD

**Issue by jungle-boogie** [pr1ntf/iohyve#230]
Hello,

Does destroying a vm with `iohyve destroy bsdguest` remove it from the `iohyve list`?

These are all ones I've destroyed and yet, I can start them up and console to them. Looks like it loads a boot loader and that's all.

```
% iohyve list
Guest       VMM?  Running  rcboot?  Description
11-release  NO    NO       NO       Sat Jan 14 22:55:03 PST 2017
11release   NO    NO       NO       Sat Jan 14 21:33:30 PST 2017
bsdguest    NO    NO       NO       Sat Jan 14 23:27:49 PST 2017
```

**Comment by pr1ntf** [comment]
As described in the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L166), running `iohyve destroy guestname` destroys it's resources in `VMM`, the kernel module that does the actual virtualization. This is named after the `bhyvectl --destroy` function, not the `zfs destroy` function. 

If you wish to remove the guest from your host, you may want to use the `iohyve delete guestname` function.

**Comment by jungle-boogie** [comment]
Fantastic! That deletes it!
