### ISSUE TITLE
"All ports busy" error when trying to connect to console of OpenBSD 6.0 installer guest

### ISSUE THREAD

**Issue by sysfu** [pr1ntf/iohyve#232]
I've created a new guest for installing OpenBSD and when I launch the installer and try to connect to the console I get an "All ports busy" error msg.

Environment:
FreeNAS-9.10.2-U1 
iohyve v0.7.7 2016/11/10 I Think I'll Go for a Walk Edition

Guest properties:
```
bargs          -A_-H_-P
boot           1
con            nmdm1
cpu            1
description    Freeswitch on OpenBSD
install        yes
loader         grub-bhyve
name           fs
os             custom
persist        1
ram            256M
size           20G
tap            tap1
template       NO
vnc            NO
vnc_h          600
vnc_ip         127.0.0.1
vnc_tablet     NO
vnc_w          800
vnc_wait       NO
```

Custom grub and device map files:

device.map
```
(hd0) /dev/zvol/bits/iohyve/fs/disk0
(cd0) /iohyve/ISO/obsd6.iso/obsd6.iso
```

grub.cfg
```
kopenbsd -h com0 (cd0)/6.0/amd64/bsd.rd
boot
```

I have another pre-existing linux guest that does not have this problem. My hunch is that only the nmdm0 console device is available and working.

**Comment by pr1ntf** [comment]
Thank you for the detailed report!

First off, is the nmdm kernel module loaded? It should appear in `kldstat`.

This is also usually a sign that you have a previous session open on `/dev/nmdm1A` and `/dev/nmdm1B`. I've ran into this in the past, so I implemented `iohyve conreset` which is documented [here](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L303). It just [runs](https://github.com/pr1ntf/iohyve/blob/master/lib/ioh-console#L32) `killall cu`. 

There is also the possibility that you have more than one `grub-bhyve` process open for a guest.

**Comment by sysfu** [comment]
`kldstat | grep nmdm`
`33    1 0xffffffff8237c000 2edb     nmdm.ko`

Running `iohyve conreset` then destroying and re-launching the guest install resolved the issue, thanks!
