### ISSUE TITLE
sparse option for zvol

### ISSUE THREAD

**Issue by heapxor** [pr1ntf/iohyve#239]
Hi,
i think there is missing -s option while creating zvol for new VM.

https://github.com/pr1ntf/iohyve/blob/master/lib/ioh-disk
line 23:
zfs create -V $size -o volmode=dev $newpool/iohyve/$name/disk$newdisk

Is it possible to add it there?

Thanks

**Comment by pr1ntf** [comment]
To be honest, I don't know what this is. :rofl: 

I'll do some Googling and take a look. At the very least, this can be a setting for guest creation time. IE `iohyve create -s thinprovisioned 8G`.

**Comment by pr1ntf** [comment]
We will not be implementing this, at least not at this time. We might be able to revisit this at a later time. As always, we would be more than happy to accept a pull request with this feature.
