### ISSUE TITLE
documentation - snap

### ISSUE THREAD

**Issue by heapxor** [pr1ntf/iohyve#240]
Hi,
could you please add more details related to the snap functionality? Can it be done while VM is running? Is there any way how to remove/delete old snaps?

thanks

**Comment by pr1ntf** [comment]
The `iohyve snap` function is currently being worked on/re-done. It's current functionality is old and outdated. 

Currently:
>Can it be done while VM is running?

Yes, there is [no check](https://github.com/pr1ntf/iohyve/blob/master/lib/ioh-zfs#L91) to see if the guest is running before a snapshot is taken. However, it's just a snapshot of the disk, not the RAM contents. Rolling back to the snapshot and starting the guest may cause the operating system to yell at you, among other things. 

>Is there any way how to remove/delete old snaps?

There is currently not a way to do this with `iohyve`. [Rolling back](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L255) to a previous snapshot deletes all snapshots made after the snapshot you are rolling back to.

**Comment by pr1ntf** [comment]
I'm going to go ahead and close this ticket. If you have any further questions regarding snapshotting, please feel free to reply to this issue and I'll re-open. Thanks!
