### ISSUE TITLE
Misleading "Missing UG feature on Intel CPU" warning

### ISSUE THREAD

**Issue by keeganspringer** [pr1ntf/iohyve#248]
I get the warning "Your CPU does not seem to fully support bhyve. Missing UG feature on Intel CPU, please upgrade to 5600 series." My CPU(Intel Xeon E5-2650) does support that feature.

[dmesg.boot.pdf](https://github.com/pr1ntf/iohyve/files/908750/dmesg.boot.pdf)

**Comment by pr1ntf** [comment]
Thank you for the report! We are aware of some dmesg issues right now. It is expected to be fixed in the [next release](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#080-goals).

Can you tell me if you are using FreeBSD, or one of it's forks, like FreeNAS?

**Comment by keeganspringer** [comment]
uname -a output: FreeBSD freebsd11 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by pr1ntf** [comment]
I've removed this check completely until better logic can be found. 

This issue is on the roadmap, and will be worked on as time comes. For now, it is up to the user to know whether their CPU supports bhyve.
