### ISSUE TITLE
iohyve import command request.

### ISSUE THREAD

**Issue by maurizio-emmex** [pr1ntf/iohyve#249]
First of all thank you for your script, I am successfully running 3 Windows 7 VM on a 64GiB box with it.
iohyve has the export command, but the import command is missing. I need import/export commands to copy a  VM to another PC.

Thanks
Maurizio

**Comment by pr1ntf** [comment]
Thanks for the kind words!

The original export command was intended to help exporting guests to other hypervisor tools. It will be removed in an [upcoming release](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#080-goals) and replaced with an improved ability to import and export guests using (abusing) zfs send and receive. 

In the mean time, remember that each guest is a dataset. If you recursively send a guest dataset from one zpool to another, for instance over ssh, it _should_ work. 

At least I have heard reports it should work with more recent versions of iohyve. 😉

**Comment by maurizio-emmex** [comment]
Thanks for your answer. If you will add the ability to transfer a VM over SSH, please include the ability of using a compressor like lz4 or lzop.  For example I have transferred my Windows 7 VM with the command:

pv -B 4M Win7.img | lz4 -c | ssh root@192.168.0.4 "lz4 -dq - Win7.img"

A compressor like lz4 or lzop works very well with Windows VM where the disk is uncompressed.

If you need an example for compression over ssh you can look at https://github.com/bolthole/zrep . I have contributed to the project for adding compression.

Regards
Maurizio
