### ISSUE TITLE
Your CPU does not seem to fully support bhyve. Missing UG feature on Intel CPU, please upgrade to 5600 series.

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#259]
Hi,

When I did iohyve setup I got this error:

Your CPU does not seem to fully support bhyve. Missing UG feature on Intel CPU, please upgrade to 5600 series.

I did a:

`sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu'`

And I got this:

```
hw.machine: amd64
hw.model: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
hw.ncpu: 32
hw.machine_arch: amd64
```

I got FreeBSD:
`
FreeBSD xtrem03 11.0-RELEASE-p9 FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017`

But the thing is my CPU does support that.

Version: iohyve v0.7.8 2017/03/05 I'd Rather be in the Delta Quadrant Edition

Thanks

**Comment by pr1ntf** [comment]
Even though it threw the error, everything should have worked correctly. 

I have [disabled](https://github.com/pr1ntf/iohyve/commit/d7ff31ea7c74c1dd52f1a67649a1d8fcdea39ebc) this check completely as of yesterday. Too many flavors of FreeBSD use different dmesg settings. 

Aside, nice metal 🤓 

```
hw.machine: amd64
hw.model: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
hw.ncpu: 40
hw.machine_arch: amd64
```
