### ISSUE TITLE
Feature: Clone without disks

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#260]
Hi,

Does iohyve support a template configuration file ? If yes you can close this one ;) 

I think it's only support to create a template from a VM ?

If it doesn't I suggest this type of variable inside a configuration file:

1) Add an option to use uefi or grub with a variable
2) Number of cpu that we can change
3) memory same like 2
4) network driver
5) disk settings
6) others options for the vm

I can do something like iohyve create -t debian.conf vmname for example and always use this file.

Will be a lot easier to create multiple vm very fast :)

**Comment by pr1ntf** [comment]
This is a great idea! We already have the [template](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L320) property that stops a guest from being started, renamed, or deleted. This is meant to allow you to use the [clone](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L238) function to create a new guest cloned from a template (or any other guest). What can make this faster in this case is adding a feature to the clone function to not clone the disks, just the guest properties.

**Comment by Firemad03** [comment]
Great, I think you need also other argument for the clone function. 

What happen if I want to clone a VM but instead of having 2 cpu I want only 1 this time ? Will be faster if the clone function can do stuff like that instead of cloning it and resize it after... but yeah I agree the only one that you need to make an exception is to resize the disk less then the VM because it's dangerous but the cpu and the memory isn't. Also resize the VM disk to a bigger one isn't dangerous 

What about clone and start after it's finish too ? :) if I want to deploy 20 VM and start them after the clone is finish.

What about clone and add a different description to the new VM ?

What about clone a VM 20 times ? :) iohyve clone N=20 (n = how much you want) instead of running it 20 times the same command.

Sorry I got lot of ideas together when you spoke about the clone function :)

**Comment by pr1ntf** [comment]
To keep from feature creep, we'll limit the clone function to it's name, *cloning*. A clone of a guest without it's disks will be able to create a specified disk size just as when you create a new guest from scratch. 

I don't foresee adding the ability to spin up more than one guest at a time like that. The zfs user property set/get actions will take FOREVER at that kind of scale. You may want to look at a different manager or different virtualization technology (jails with iocage has this ability, and accomplished this by ditching zfs user properties for ucl). If you really need that kind of stuff, you could also script iohyve itself at that layer. 

Feel free to respond back, it's quite possible I have no understanding of what you are trying to accomplish 😉 .

**Comment by Firemad03** [comment]
You are right about the clone thing it's better to keep it simple.

Anyways when we will be able to clone the guest properties I guess after that I can edit the file template (well you need to store it somewhere heh) and change the value of the cpu, memory, description etc. if I want to create another VM bigger for example.

All my issues is covered with the new function.

**Comment by pr1ntf** [comment]
Friendly reminder that you can set more than one property at a time `iohyve set bsdguest ram=2048 cpu=2 description="My Great Guest"`. Cloning a guest without it's disks will be put on the list. Should be done soon :tm:. 

😉

**Comment by Firemad03** [comment]
> Should be done soon ™️

👍

**Comment by pr1ntf** [comment]
This issue has been added to the [roadmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0).
