### ISSUE TITLE
iohyve setup on actual zpool not a path

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#261]
Hi,

I think iohyve can only be installed inside a pool like tank but not in tank/dataset ?

I did an iohyve setup on tank/dataset.

iohyve installed the folder in /iohyve (not in my tank root... my / is on another disk that contain my FreeBSD installation)

When I tried to fetch an iso it said something like "cannot create 'tank/iohyve/ISO/os.iso: parent does not exist" and I checked the tank and yes the error is right the folder isn't there. 

I found it in /iohyve/ISO instead because later I tried another iohyve setup in my tank pool but it said that iohyve installed a secondary pool... ok but how do I delete the wrong pool one if I want to start over the iohyve setup ?

I searched the man but can't find a destroy iohyve pool mount setup something like that ?

Yeah I can destroy the zfs dataset or pool and start it over from there but I thought it will be nice to have it in iohyve command line.

I think a got a bug and a feature together :)

Note: If you have multiple pool the iohyve fetchiso need an extra argument to download it to the pool that I will choose. Something like: iohyve fetchiso os.iso pool=tank because sometime I want the iso somewhere else instead but yes I could do a copy of the file too heh ;)

**Comment by Firemad03** [comment]
Allright I found how to remove everything: 
umount everything that I used
delete the iohyve folder
zfs destroy 
restart it over :)

**Comment by Firemad03** [comment]
I tried again with iohyve setup pool=tank but iohyve said that it already exist in it. I checked in tank with ls but I don't find anything.... weird :) I guess I'm stuck for now heh

**Comment by pr1ntf** [comment]
You can only setup iohyve on a zpool, not a dataset. You will have to manually remove (destroy it and it's children) any iohyve datasets created erroneously by hand. 

The ISO dataset will only live on the primary zpool (the one you originally setup iohyve on).

A simple output of `zfs list | grep iohyve` should point me in the right direction of what datasets to destroy.

**Comment by Firemad03** [comment]
Thanks about the zfs list. I don't know why I didn't think about that... ;) I did again the iohyve setup and it's working 100% :)

I'm used to have multiple dataset inside a pool. That's the reason why I did this mistake.

Is it safe to make iohyve setup in a pool that have multiple dataset ?

**Comment by pr1ntf** [comment]
iohyve really doesn't care who else is in the pool, as long as it has one to be in. 💦 

iohyve will then create datasets under it's own dataset (as you can see in the raw zfs list output. )

**Comment by Firemad03** [comment]
Ok I understand better :)

I think you should make an error if someone do something like I did.

If iohyve setup see a / after the pool name then trow an error :) it's a suggestion.

**Comment by pr1ntf** [comment]
Totally, I'm going to leave this open to write up a simple check (like making sure the pool is an actual pool).

Thanks again for all your input today!

**Comment by Firemad03** [comment]
>  iohyve will then create datasets under it's own dataset

Can I compress the dataset with lz4 ? I need to do it after the iohyve setup I guess since I don't have the option but yeah I guess iohyve will inherit the stuff from the pool but what happen if someone want something different for the dataset of iohyve ? :)

I think it's a good idea to add the option too. Some people will like no compression on the pool but for the iohyve dataset they want gzip or lz4 or etc. 

What do you think ?

Sorry I know it should be on another issue :)

**Comment by pr1ntf** [comment]
I would let the user decide whether or not they want to enable compression, at their own discretion. I understand it's just as simple as `zfs set compression=type pool/dataset`. I don't think that warrants a new feature/function of iohyve just yet though.

**Comment by Firemad03** [comment]
I guess maybe just somewhere in the man to explain it how will be helpful like a warning in the setup description in the man that we need to enable it after for the compression.

**Comment by pr1ntf** [comment]
I'd prefer to keep suggestions on zfs tuning to the pros like Allan Jude and Michael Lucas (I recommend their [book](https://www.michaelwlucas.com/os/fmzfs)).

If anything, if someone does write up something, we would be more than happy to mirror it in the iohyve wiki, under the how-to journal section.

**Comment by Firemad03** [comment]
Thx for the book, I'll definitely check it out ! zfs is such a wonderful technology and I didn't know someone wrote a book about that ;)

**Comment by Drizzt321** [comment]
Just encountered this issue, which is annoying to me. I want iohyve to put everything into a pool that I control the name of. And it's VERY jarring to have it accept `iohyve setup pool=tank/bhyve` and happily setup the sub-pools underneath, but then when it comes to this it chokes and now I come to find out it doesn't how I expected it to support. I thought the setup would create some configuration that future commands would reference to know where the root dir for all of the stuff would live. Seems odd to me. 

Would you be open to a pull that goes through and makes those changes? Essentially having a base path variable which everything operates off of instead of grepping on the zfs list to find the top level zpool?

**Comment by pr1ntf** [comment]
@Drizzt321 We are always looking for good PR's! Check out the [contributing](https://github.com/pr1ntf/iohyve/blob/master/CONTRIBUTING.md) page for more info!
