### ISSUE TITLE
renameiso bug path

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#264]
Hi,

I got a weird bug with the renameiso:

![image](https://cloud.githubusercontent.com/assets/24792889/25766588/6a6dd90e-31c1-11e7-801e-bd742548e910.png)

This section:
/iohyve/ISO/debian-8.7.1-amd64-netinst.iso/debian-8.7.1-amd64-netinst.iso

But iohyve did the change anyways...

![image](https://cloud.githubusercontent.com/assets/24792889/25766646/aef8a82e-31c1-11e7-8a5c-5a1438991f7c.png)

Or the result with iohyve:

![image](https://cloud.githubusercontent.com/assets/24792889/25766696/0700bafc-31c2-11e7-9fd0-a1983275df55.png)

I did it again just to be sure:

![image](https://cloud.githubusercontent.com/assets/24792889/25766751/704df560-31c2-11e7-822b-a683b24bb588.png)

Same problems and results. I don't know what I did wrong. 

It's very easy to reproduce ;)

Version: iohyve v0.7.8 2017/03/05 I'd Rather be in the Delta Quadrant Edition

**Comment by pr1ntf** [comment]
Can you post the output of `zfs list | grep ISO`? Thanks for the screenshots. You can also post [code blocks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
```
\\\///\\\///\\\///\\\///
Pre formatted text here
\\\///\\\///\\\///\\\///
```

**Comment by Firemad03** [comment]
`ES-SAS-Z/ISO-Windows         6.33G  2.58T  6.33G  /mnt/ES-SAS-Z/ISO-Windows`
`SSD-MIR/VM2/iohyve/ISO         96K   221G    96K  /iohyve/ISO`
`SSD-MIR/iohyve/ISO            239M   221G    96K  /iohyve/ISO`
`SSD-MIR/iohyve/ISO/debian     239M   221G   239M  /iohyve/ISO/debian`

**Comment by Firemad03** [comment]
I know the SSD-MIR/VM2 is my mistake with the other issue that I had because I did a setup inside a dataset :)

**Comment by Firemad03** [comment]
``` root@xtrem03:/usr/local/share/uefi-firmware # iohyve install srv001 debian                                                         root@xtrem03:/usr/local/share/uefi-firmware # bhyve: Could not open backing file: /iohyve/ISO/debian/debian: No such file or directory ``` 

I'm stuck can't create any vm lol

**Comment by Firemad03** [comment]
Ok I found the reason and how to correct it: it's related about the other issue about that I installed first iohyve in a dataset. 

I did a umount -f of everything that contain SSD-MIR/VM2 and now it's find the correct path.

Well I think I will destroy the pool completely and start it over for iohyve :) the dataset bug did lot of damage.

I don't know if you need to fix something with the bug that I had or not.

#261

**Comment by Firemad03** [comment]
I thought it was related but it isn't related to #261 

Now my setup is fine and I was able to install a 100% Debian vm without a problem.
I only did a restart of my freebsd and check this out when I tried another vm:
```
root@xtrem03:~ # iohyve create srv003 10G
Creating srv003...
root@xtrem03:~ # iohyve install srv003 debian8.7.1
Installing srv003...
bhyveload: Could not open '/iohyve/ISO/debian8.7.1/debian8.7.1'
root@xtrem03:~ # virtual machine cannot be booted

root@xtrem03:~ # iohyve renameiso debian8.7.1 debian
Renaming ISO debian8.7.1 to debian...
mv: rename /iohyve/ISO/debian8.7.1/debian8.7.1 to /iohyve/ISO/debian8.7.1/debian: No such file or directory
cannot open 'SSD-MIR/iohyve/ISO/debian8.7.1': dataset does not exist
root@xtrem03:~ # iohyve install srv003 debian
Installing srv003...
bhyveload: Could not open '/iohyve/ISO/debian/debian'
root@xtrem03:~ # bhyve: Could not open backing file: /iohyve/ISO/debian/debian: No such file or directory
```

iohyve v0.7.8G 2017/03/05 I'd Rather be in the Delta Quadrant Edition

```
root@xtrem03:~ # zfs list | grep ISO
ES-SAS-Z/ISO-Windows                6.33G  2.58T  6.33G  /mnt/ES-SAS-Z/ISO-Windows
SSD-MIR/iohyve/ISO                   239M   192G    96K  /iohyve/ISO
SSD-MIR/iohyve/ISO/debian8.7.1.iso   239M   192G   239M  /iohyve/ISO/debian8.7.1.iso

```

**Comment by pr1ntf** [comment]
`debian8.7.1`doesn't exist. You forgot to add the `.iso`
