### ISSUE TITLE
Suggestion: UEFI Firmware

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#266]
Hi,

https://wiki.freebsd.org/bhyve/UEFI

`pkg install bhyve-firmware`

All firmware is located there
`/usr/local/share/uefi-firmware`

Why not use by default the default path for UEFI and if it doesn't exist trow a:

> You must set a firmware file property to use UEFI. Please check https://wiki.freebsd.org/bhyve/UEFI

I think it will be a lot easier. 

Also you can update the man page about this information too ;)

I had to search stuff on how to do it in google and I think it should be added somewhere in the man at minimum ;)

**Comment by pr1ntf** [comment]
I've added verbage to the man page entry on the `fw` property. It's been pushed to `develop` and will be merged to `master` in time.
