### ISSUE TITLE
Set function requires check if guest exists

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#267]
Hi,

I know that you need to do a create before a set but when I created vms I forgot for one vm and the set command created the folder.

I expected an error but I didn't get any.

I tried a destroy and remove and yes the destroy deleted the vm but the remove didn't delete the folder.

If I try to do it manually in /iohyve off course it's said the device is busy because it's mounted. So I had to umount it.

**Comment by pr1ntf** [comment]
Set function requires check if guest exists
