### ISSUE TITLE
Unhandled ps2 keyboard command 0xf6

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#268]
I don't know why I got this error but I got it after my installation of a Debian 8.7.1 in a vm 

The installation did well but at the end the setup asked to reboot and I got this output in my shell not in the console:
`Unhandled ps2 keyboard command 0xf6`

My vm console was stuck (well I think it's normal because the vm stopped) so I add to manually start the vm manually with iohyve start

I expected a restart ;)

**Comment by pr1ntf** [comment]
This is a [known issue](https://forums.freebsd.org/threads/58321/) in bhyve.

**Comment by pr1ntf** [comment]
(The error code may be different, but the noisy fbuf related errors are a known issue)
