### ISSUE TITLE
RTC Wrong in Windows 10 VM

### ISSUE THREAD

**Issue by JRGonz** [pr1ntf/iohyve#270]
Is it possible to have an option to have an RTC offset so Windows uses time properly? I am running into issues where the RTC is off. 

Possibly using: 
https://reviews.freebsd.org/D1385

**Comment by JRGonz** [comment]
Never mind. Seems a guest fix is already around to force windows to use UTC time from the RTC. I guess you can treat it like you would a dual boot system...

https://wiki.archlinux.org/index.php/Time#UTC_in_Windows

Would be nice if this could be done from bhyve still tho. If it's possible.

**Comment by pr1ntf** [comment]
This seems to be more of an issue with bhyve as opposed to iohyve. 

Please note that you can change the bhyve clock to use UTC or not using the [UTC](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L324) property.
