### ISSUE TITLE
suse support?

### ISSUE THREAD

**Issue by plato79** [pr1ntf/iohyve#274]
Hi, tried several times with "openSUSE-Leap-42.1-DVD-x86_64.iso"

Here is the VM properties:
```
Getting suse iohyve properties...
bargs                  -A_-H_-P
boot                   0
con                    nmdm1
cpu                    8
description            Wed Jun  7 00:12:27 +03 2017
install                yes
loader                 grub-bhyve
name                   suse
os                     suse
persist                1
ram                    8G
size                   100G
tap                    tap1
template               NO
vnc                    NO
vnc_h                  600
vnc_ip                 127.0.0.1
vnc_tablet             NO
vnc_w                  800
vnc_wait               NO
```

Is it not supported yet?

**Comment by pr1ntf** [comment]
Sorry, `suse` is not a valid `os` [property](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L331) at the moment. If you would like this added, we can turn this into a feature request, and we will take a look at adding this Linux distribution to the list of supported OS's. 

You may want to look at using the `os=custom` setting explained [here](https://github.com/pr1ntf/iohyve#use-your-own-custom-grubcfg-and-devicemap-files) if you need it now. 

You may also want to see the inner workings of other Linux `grub.cfg` files that iohyve creates as a [reference](https://github.com/pr1ntf/iohyve/blob/master/lib/ioh-guest#L373). (If you get it working, send in a PR, and we'll take a look at getting it merged!)

**Comment by pr1ntf** [comment]
I'm going to close out this issue. If you still have issue with this matter, feel free to comment and I can re-open. If you have a question on another matter, please open a new issue. 

Thanks!
