### ISSUE TITLE
Create better way to manage virtual harware

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#37]
I think iohyve needs a better way to manage harware that needs to begin in the 'create' stages. 
Support for multiple disks, NICs, and more. (ahci-hd/virtio-blk, zvol/emptyfile, hostbridge emulation, passthrough devices, etc...)

Even though most of these things aren't implemented or not a priority, if iohyve grows, it would be nice to standardize now. See 'bhyve slot emulation' in the bhyve man page.

**Comment by pr1ntf** [comment]
Closing due to milestone creation.

**Comment by pr1ntf** [comment]
Scratch that, I don't know how to git.

**Comment by pr1ntf** [comment]
Need to be able to create new disks to attach. 
Will need to be able to attach new virtio or ahci disks. 
Ability to move disks between guests. 

Need a way to store these and passthrough in zfs props.

**Comment by 3add3287** [comment]
I have implemented something on my end and it's part of [pull request #40](https://github.com/pr1ntf/iohyve/pull/40).
It basically (ab)uses zfs property "iohyve:pcidev:<random>=<specification>" to generate as many devices as wanted.The specification matches that of the bhvye "-s" flag, except that slot/function/bus is not included as that is automatically generated at runtime.

**Comment by pr1ntf** [comment]
PR looks pretty fantastic :+1: 

Have you tried passing through disk devices?

**Comment by 3add3287** [comment]
No, none of my test boxes had a 2nd disk controller that I could test with.

**Comment by pr1ntf** [comment]
Closing since the pcidev thing works very well.
