### ISSUE TITLE
disk image naming

### ISSUE THREAD

**Issue by 3add3287** [pr1ntf/iohyve#41]
Right now imags/zvols are named "zroot/iohyve/$name/$name-0.img"
Including the name twice seems redundant. With zvol the default one can argue it's no longer an image and hence dropping the img suffix would make sense.

I suggest the zvols be renamed to "zroot/iohyve/$name/diskN" where N starts with 0 as it would provide a cleaner look

**Comment by pr1ntf** [comment]
This is a fantastic idea that shouldn't take very long to implement. Thanks! :+1:

**Comment by pr1ntf** [comment]
Implemented as of v0.5.6.
