### ISSUE TITLE
Allow setting MAC address for tap device

### ISSUE THREAD

**Issue by 3add3287** [pr1ntf/iohyve#42]
Bhyve makes it possible to set the MAC address for a virtio-tap interface instead of just randomly generating one. "-s <slot>,virtio-net,tap2,mac=xxxx:xx:xx:xx:xx"
This should be possible to configure per guest using zfs properties

**Comment by pr1ntf** [comment]
Reading the wiki, it looks like bhyve has its own MAC address allocation.
https://wiki.freebsd.org/bhyve

```
58-9C-FC
```

Then should we add something generated at random?

**Comment by 3add3287** [comment]
My proposal is not to change the default behavior (letting behyve deal with MAC addresses automatically) but to let the user manually override the MAC address based on his needs, let's say with locally administered addresses.

**Comment by mokou** [comment]
+1

**Comment by pr1ntf** [comment]
Loud and clear. :+1:

**Comment by pr1ntf** [comment]
This has been implemented. 

`iohyve set guestname mac=00:01:02:03:05:08`
