### ISSUE TITLE
iohyve man example rename missing rename option.

### ISSUE THREAD

**Issue by polishdub** [pr1ntf/iohyve#44]
Line 798 of iohyve:
Currently:
  `iohyve FreeBSD-10.1-RELEASE-amd64-bootonly.iso freebsd10.iso`
Change:
  `iohyve rename FreeBSD-10.1-RELEASE-amd64-bootonly.iso freebsd10.iso`

**Comment by pr1ntf** [comment]
Fixed.
Thanks for the good eye!
