### ISSUE TITLE
No way to delete property. 

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#47]
iohyve currently does not handle deleting of properties for things such as pcidev.

**Comment by pr1ntf** [comment]
Function is now added. No documentation yet, but it's there. 
`iohyve rmpci bsdguest pcidev:2`

**Comment by Braintelligence** [comment]
This issue is kind of confusing. All you implemented seems to be a method to remove pcidev properties but I can't remove a set mac property for example.

**Comment by pr1ntf** [comment]
This issue is over a year old. It was created as a place holder to remind me to write something. 

I never created a function to remove other properties, because I was worried folks would delete the wrong thing and mess things up (shooting one's foot). With the introduction of MAC properties, and future properties listing network bridges, you make a good point, this should be fully implemented. 

I am going to re-open this issue as another reminder to remove the `grep pcidev:` from the check [here](https://github.com/pr1ntf/iohyve/blob/master/lib/ioh-zfs#L46), and on the man page [here](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L217).

For now, take a look at the `zfs inherit` function:

```
zfs inherit  -r iohyve:$property $poolname/iohyve/$guestname
```

**Comment by Braintelligence** [comment]
Thank you for considering 😸

**Comment by pr1ntf** [comment]
Thanks for bringing it to my attention! 🍻 🌮

**Comment by pr1ntf** [comment]
This has been fully [implemented](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L217)

Thanks again!

**Comment by Braintelligence** [comment]
Wow you're blazingly fast. Kudos to you :D.

**Comment by pr1ntf** [comment]
Nah: I just removed a grep and renamed the function. I am just a mere mortal.
