### ISSUE TITLE
Add ability to grow zvols

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#53]
Add the ability to grow zvols.

**Comment by mischapeters** [comment]
LVM is a bad idea. Tried installing Debian 8 with LVM, and it's hanging in GRUB for some reason.

**Comment by pr1ntf** [comment]
I had this issue in my original go around with `grub-bhyve` back when I was still using raw files for disks, not zvols. If I recall, RAM needed to be at least 512M and some other gotcha.

**Comment by pr1ntf** [comment]
iohyve can now resize disk images. This will tend to break things if you are not careful. 

```
iohyve resize bsdguest disk1 16G
```
