### ISSUE TITLE
"service iohyve stop" won't wait for the VMs to shut down

### ISSUE THREAD

**Issue by espadolini** [pr1ntf/iohyve#54]
I can foresee a situation in which the shutdown process will eventually SIGKILL the bhyve processes because they're taking too much time to shutdown; perhaps either `iohyve scram` or just `service iohyve stop` should wait for the VMs to be done with their shutdown?

**Comment by pr1ntf** [comment]
Interesting thought. Thanks for the info. At some point the guest will need to be SIGKILL'd if it's hanging and causing the host machine to not shut down.

**Comment by pr1ntf** [comment]
A wild man page appears: https://www.freebsd.org/cgi/man.cgi?query=rc.subr&sektion=8&n=1

Idea is totally from Matt's script.

**Comment by pr1ntf** [comment]
#82 also needs a way to find all iohhyve-owned PID's.

**Comment by pr1ntf** [comment]
`wait_for_pids` has been implemented in the `scram` function. 

It only works when called with the rc script.
