### ISSUE TITLE
Description in ZFS properties

### ISSUE THREAD

**Issue by mischapeters** [pr1ntf/iohyve#55]
It would be seriously awesome if you would allow for a description of the VM to be stored in ZFS properties. And to be displayed with "iohyve running" and "iohyve list".

**Comment by pr1ntf** [comment]
`iohyve running` and `iohyve list` will be consolidated soon. I like this idea. Are you just looking for a custom property with a quoted string? I.E. `iohyve set obsdguest description="OpenSMTPd Maildrop"`

**Comment by mischapeters** [comment]
Great that both list will be consolidated, does that mean you have all VMs in one place showing if they are running or not?

Indeed a property with a quoted string. To have either customer info or indeed more information on the VM itself if the name of the VM is not providing enough info.

**Comment by pr1ntf** [comment]
You can now add a quoted string to the description property. You have to put the string in between double quotes, and you can't have an equals sign. To get away with this, I leveraged good ol' `sed` to turn spaces into underscores. 

This is not in list yet, though. I consolidating all of this lists iohyve has at the moment to just a few, with better information. 

There will be the default output that will output the name, if it's in /dev/vmm, if it is running, the os property if it rcboots, then description. The second `-c` will be all the consoles, and noting whether it is active or not. The third is the same but for the tap interfacees `-t`. The last one is the snapshots `-s`.

**Comment by pr1ntf** [comment]
You can now see the description when running `iohyve list`

**Comment by mischapeters** [comment]
Awesome dude!

**Comment by mischapeters** [comment]
Love the new layout... very cool!
