### ISSUE TITLE
iohyve should allow for UTC RTC

### ISSUE THREAD

**Issue by espadolini** [pr1ntf/iohyve#56]
I don't know whether or not it's worth it to have it as an option, but there should be a way to pass `-u` to `bhyve` so that guests have a UTC clock.

**Comment by pr1ntf** [comment]
Thanks for the great idea! _Shouldn't_ be too difficult to implement. I'll add it to the list.

**Comment by pr1ntf** [comment]
As of version 0.6.5 you can now do this. I've explained this in the readme.
If you want to add `-u` to your bhyve arguments, you can run `iohyve set guestname bargs="-A -H -P -u"`

Been wanting to do something like that for a while, you kicked me into doing it, thanks! :grinning:
