### ISSUE TITLE
Adding in disk image files to an existing iohyve guest

### ISSUE THREAD

**Issue by ghost** [pr1ntf/iohyve#66]
I have an old bhyve linux guest that I would like to run in iohyve. This guest was set up using the instructions at https://www.freebsd.org/doc/handbook/virtualization-host-bhyve.html
This means that I have a linux-guest.img file which was made available to the guest using the virtio-blk option. Is there any way to add this file to an iohyve guest which already has one disk configured (as /zvol/dev/iohyve/$name/disk0). I would like to add in the .img file and transfer data over to the new disk.

**Comment by pr1ntf** [comment]
Well, iohyve uses the `ahci-hd` for block devices. I'm not sure if this would work for images that were created for `virtio-blk`.

I have done work in the past outputting the contents of a zvol to a file and vice versa. 
I would think that as long as the zvol size is correct, you could try something like `dd if=/path/to/linux-guest.img of=/dev/zvol/poolname/iohyve/guestname/disk0`. 

This, however, is totally unsupported and may break things. Use at your own risk.
