### ISSUE TITLE
Support more than one bridge on the host machine

### ISSUE THREAD

**Issue by ramijebara** [pr1ntf/iohyve#70]
Hi 

I needed my virtual machines to bind to 2 different networks on 2 different NICs. looking at the code it seems like iohyve only supports bridge0 with that being hard coded in the script. 

Since in this case I needed both bridge0 and bridge1, I changed __prepare_guest to attempt to read a bridge value, if it finds it, it will use it else everything works as expected in the application. It’s a bit of a hack as it expects any bridge other than bridge0 to be up and ready to go. 

Please feel free to use this code if you find it useful. 

Git diff attached
[iohyve.txt](https://github.com/pr1ntf/iohyve/files/32570/iohyve.txt)

**Comment by pr1ntf** [comment]
Cool stuff! :smile:

Right now bridge0 is indeed hardcoded into iohyve. I've been ~~banging my head against the wall~~ playing with restructuring the networking in iohyve. One of the steps to having a NAT in iohyve like in #64 is that iohyve will be the ability to support multiple bridges. You will be able to assign the network with something very similar to what you have done there. 

Keep up the great hacking!

**Comment by ramijebara** [comment]
Thanks!

After I sent the patch I was thinking about it some more and did a small adjustment that may even be better. 

Phase 1
When you create a machine always set a bridge attribute, e.g. bridge0. 

Then all you have to do is read the attribute when a machine is created.

This is 2 lines of code. see patch inline later in the email.

Phase 2
Bootstrapping this automatically is where it gets complicated but if we can set a global attribute on iohyve that maps the bridge to the interface, 

e.g.
iohyve set bridge0=igb0
iohyve set bridge1=igb1

then the bootstrap process will read the bridge<*> keys and values 

then for each $key $value 
  check if the bridge exists
    check if it is up and bound to the right $value
    Warn if there are issues
  if does not
    ifconfig $key create
    ifconfig $key addm $value
        ifconfig $key up
   fi

I hope you find this helpful. Small patch below:

Thanks again for this great tool!

diff --git a/iohyve b/iohyve
index e5549d3..c494892 100755
--- a/iohyve
+++ b/iohyve
@@ -427,6 +427,7 @@ __create() {
        zfs set iohyve:autogrub='\n' $pool/iohyve/$name
        zfs set iohyve:description=$description $pool/iohyve/$name
        zfs set iohyve:bargs=-A_-H_-P $pool/iohyve/$name
- zfs set iohyve:bridge=bridge0
  }
  
  # Install guest
  
  @@ -612,6 +613,7 @@ __prepare_guest() {
      local dataset="$(zfs list -H -t volume | grep $name | grep disk0 | cut -d '/' -f 1-3 | head -n1)"
      local pci="$(__get_zfs_pcidev_conf $dataset)"
      local tap="$(zfs get -H -o value iohyve:tap $dataset)"
- local bridge="$(zfs get -H -o value iohyve:bridge $dataset)"
      # Setup tap if needed
      if [ $tap ] && [ $tap != "-" ]; then
              if [ $tap != "tap0" ]; then
  @@ -621,7 +623,8 @@ __prepare_guest() {
                      if [ -z $tapif ]; then
                              # create tap interface
                              ifconfig $tap create
-                           ifconfig bridge0 addm $tap
-                         # add tap interface to bridge
-                         ifconfig $bridge addm $tap
                      fi
              fi
              # Add a virtio-net pci device for the tap

**Comment by pr1ntf** [comment]
Right now, and probably in the future with "virtual switches" you can set global properties with `iohyve setup`. Right now with support for only one bridge, you can attach it with `iohyve setup net=igb0`. In the future this will turn into something like `iohyve setup bridge0=igb0 bridge1=igb1 nat1=bridge1`. This way you can set a guest up with something like `iohyve set bsdguest tap=tap14 bridge=bridge1` etc...

> Thanks again for this great tool!

Thanks for using and hacking on it!

**Comment by lunetics** [comment]
Any timeframe on that? Thinking of using iohyve for pfsense (quad nic)

**Comment by pr1ntf** [comment]
I would say by Mid-December.....ish? Hopefully sooner, but this is done in my spare time. 

Multiple bridge support (and thus multiple virtual NIC support) needs to happen before a virtual NAT is implemented. So it's near the top of the list. 

I'm working on fixing up `iohyve set` and `iohyve create` in regards to setting multiple properties. After that, there are many bugs in open issues that need some attention. Part of that is utilizing `grub-bhyve` properly. Then after that, it's back to playing with the NAT stuff. 

That being said, I am always open to ideas, suggestions, and pull requests. :smile:
