### ISSUE TITLE
usb device

### ISSUE THREAD

**Issue by Eresia999** [pr1ntf/iohyve#72]
Hi, is it possible to pass a usb device to a VM?

**Comment by pr1ntf** [comment]
Although I have not specifically tested passing a USB device to a guest, `iohyve` does have the ability to pass through PCI devices. 

Info on `iohyve` specific pass through is located in the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L183).

You can also find out more information on `bhyve` pass through in general at their [man page](https://www.freebsd.org/cgi/man.cgi?query=bhyve&sektion=8) or their [wiki](https://wiki.freebsd.org/bhyve/pci_passthru) on the subject. 

If you get it working, document it! We would love to add it to the wiki.

**Comment by Eresia999** [comment]
Yes, the problem was the bhyve pass through, I was able to pass a ethernet device but not a usb 3.0 device, the xhci1 won't become a ppt so the problem is not in iohyve. I think the first problem is the xhci driver but I don't know how to disable it from FreeBSD, I've tried to disable from the bios but no way, the xhci1 become xhci0 so the driver is still load...

**Comment by Eresia999** [comment]
Done!!
I 'll document it, but my english is not good, can I sent you my steps here and you make the wiki?

**Comment by pr1ntf** [comment]
Hooray! :smile: 

I have temporarily opened the wiki to editing. You should have the ability to create a new page.

**Comment by pr1ntf** [comment]
Great work! 

I'm going to fix the formatting just a bit, but your English is great!

**Comment by Eresia999** [comment]
Thank you, 
Hope to be useful and Google translater help me a little bit :)

**Comment by itchk** [comment]
where can i find the documentacion of pass a usb device to a VM (bhyve) ?

**Comment by Eresia999** [comment]
https://github.com/pr1ntf/iohyve/wiki/USB-3.0-PCI-Controller-Pass-through
Try to look at this

Inviato da iPhone
