### ISSUE TITLE
Add documentation on proper cleaning after install and property change.

### ISSUE THREAD

**Issue by skarekrow** [pr1ntf/iohyve#80]
It will bail out:

```
vm_setup_memory: Invalid argument
[brandon@devbox] ~% Unable to setup memory (22)
```

This leaves an entry in `/dev/vmm`. Which requires the user to do `iohyve destroy VM`

**Comment by pr1ntf** [comment]
Can you please post what the ram property is?

The bhyve [man page](https://www.freebsd.org/cgi/man.cgi?query=bhyve&sektion=8) allows for size suffixes. 

If you changed the memory size and tried to run before destroying, that could make things fail in this way as well. 
You can not change the memory of a guest that is in VMM.

**Comment by skarekrow** [comment]
You're correct, I did not run `iohyve destroy` before changing the suffix to `G`. I didn't see this mentioned in the documentation. Did I miss it?

**Comment by pr1ntf** [comment]
It's a bhyve thing. It would be prudent to put a mention of this in the man page for the `iohyve set` function I guess. I'll keep this open as a reminder.

**Comment by pr1ntf** [comment]
Added documentation that clarifies the `destroy` function.
