### ISSUE TITLE
Stop hung GRUB instances

### ISSUE THREAD

**Issue by skarekrow** [pr1ntf/iohyve#81]
Steps to reproduce:

```
iohyve create VM 20G
iohyve install VM ISO (Exit out of console, do not install)
iohyve stop VM
iohyve start VM
```

At that point trying to call `iohyve stop VM` will show this:

```
[brandon@devbox] ~% sudo iohyve stop VM
Stopping VM...
usage: kill [-s signal_name] pid ...
       kill -l [exit_status]
       kill -signal_name pid ...
       kill -signal_number pid ...
[brandon@devbox] ~% ps -ax | grep iohyve
31806  2  S       0:00.00 /bin/sh /usr/local/sbin/iohyve start VM
31824  2  R       0:13.80 bhyveload -m 8192M -d /dev/zvol/tank/iohyve/VM/disk0 -c /dev/nmdm0A ioh-VM
31841  2  S+      0:00.00 grep iohyve
```

This requires the user in this example to kill both `31806` and `31824`. If you just kill `31824` you get this error:

```
vm_reinit: Device busy
bhyve: could not activate CPU 0: Device busy
```

Afterwards you also have to call `iohyve destroy VM` to finally stop things.

**Comment by pr1ntf** [comment]
Add a function to kill the start demon and the grub demon if the guest hasn't booted yet. 

If you just kill grub, it will start over because the start loop.

**Comment by jungle-boogie** [comment]
yes, thank you @skarekrow for reporting this. I've see this but I didn't know the exact cause.

Thanks @pr1ntf for working on this.

**Comment by pr1ntf** [comment]
You can now run `iohyve forcekill guestname` to `kill -9` and `bhyvectl --destroy` the guest.

**Comment by skarekrow** [comment]
\m/
