### ISSUE TITLE
Correctly utilize grub2-bhyve

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#83]
Instead of piping stuff to `grub-bhyve` we should properly utilize all of it's features, specifically relating to the `grub.cfg` files. We might even go as far as custom `grub.cfg` files.

**Comment by EpiJunkie** [comment]
One thing that `iocage` does for it's `fstab` files is place the file in the jail's dataset at `/iocage/jails/jail-id/`. Something similar could be done here to place the `grub.cfg` file at `/iohyve/guest-name/`. This way the file stays with the guest through `zfs send | zfs recv`, stays current with snapshots, and also can be easily reference from `iohyve`.

I imagine initially populating the `grub.cfg` file would be easy enough with piping output, however modifications would be more difficult especially if the file was modified by the user.

Is there a use-case in mind? I pretty much have only used `grub-bhyve` once for a guest and iohyve took care of it for me. But I would certainly like to help if I can.

**Comment by pr1ntf** [comment]
This is the case. We will be placing the custom `grub.cfg` along with the `device.map` which is already in the dataset currently. 

More information can be found on the [iohyve Wiki](https://github.com/pr1ntf/iohyve/wiki) in [Roadmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0) and [Guest Support](https://github.com/pr1ntf/iohyve/wiki/Guest-Operating-System-Support)

**Comment by churchers** [comment]
A few notes of interest on this I've picked up recently (some of which seem obvious to me now).

It seems that the `grub-bhyve` options are used to specify where inside the guest boot partition to find the `grub.conf` file. You can't point it at a file on the bhyve host. (unless there's some feature I'm not aware of. It would be great if `grub-bhyve` had an option to specify a local config file)

It looks like `hd0,msdos1` and `hd0,1` function the same. Probably well known to actual Linux users.

I was able to get Alpine to boot automatically just by creating a file on the guests boot partition (`/dev/vda1` in my case) containing the below, then using the `-d` & `-g` options to point grub-bhyve at it.

```
timeout=15

menuentry 'Alpine (bhyve)' {
    root=hd0,1
    linux ...
    initrd ....
}
```

Not sure if the root line is required as I'm specifying it to grub-bhyve, but haven't tested without it yet.

This works great for me as I don't need to pipe in any commands, so grub-bhyve can run on the nmdm. This means the user can access the bootloader using the console command, but the guest should boot the default menu entry automatically anyway without interaction.

The problem of course is that (as far as my knowledge goes) it's not trivial to manage these files from the host if they live inside the guests boot partition. The ideal would be users installing grub2 in the guest (if required) and managing grub2 config using Linux tools, then just making sure `grub-bhyve` finds the file, but that requires additional work from the user. At the moment I'm still sticking with host based grub files that are piped in, which is all very well as long as the commands work.

**Comment by EpiJunkie** [comment]
This is something I have recently noticed as well. My `loader:grub-bhyve` experience is limited to 3 Linux distros: [RHEL7.2, CentOS 7](https://github.com/pr1ntf/iohyve/pull/125), and Debian 8.3. On all three, the `grub.cfg` resides on the guest system and at `/grub` or `/grub2`. Which makes sense as many Linux distros use `grub` to boot.

_I think_ I remember it was expressed this project does not want to maintain a list of distro configs for booting with `grub-bhyve`. Maybe instead there could be user set properties `iohyve:grub.cfg-path` and `iohyve:grub.cfg-filename` that gets used using the `-d` and `-g` flags. Using these properties instead would allow us to consolidate a large chunk of code (lines 489-586) in `iohyve`. The 'database' could then be maintained as a part of the man page "Use these properties for these distros" which is not so different than telling the end user to `iohyve set bguest os=d8lvm`. Although the `os` property would be largely arbitrary in this scenario.

Also another interesting thing to note. It seems grub2-bhyve has the ability to map to `(host)` in the `device.map`. This is in addition to the commonly used `(cd0)` and `(hd0)`. We probably do not want to be maintaining the `grub.cfg` file from the host as the guest should be doing that instead. But the `(host)` map is interesting option.

Excerpt from [README.md at grub2-bhyve git page](https://github.com/grehan-freebsd/grub2-bhyve/blob/master/README.md).

> There is an additional device, "(host)", that is always available and allows the host filesystem to be accessed.

**Comment by pr1ntf** [comment]
Thank you for all the help and comments, @churchers and @EpiJunkie that's a huge help. I was indeed planning on storing the `grub.cfg` and `device.map` on the host, then telling the `grub.cfg` to look elsewhere. I've gotten this working by hand, but it's now more a matter of squishing this idea into `iohyve` while not breaking too many things for people who already use `grub-bhyve` and will be updating. 

I'll keep everyone posted on that progress in this thread so we can continue the discussion. 

Again, thanks for the help!

**Comment by churchers** [comment]
How did I not think to read that grub-bhyve github page in more detail. It really could do with a man page!

So it seems the following is probably the best of all worlds

```
grub-bhyve -c /dev/nmdmXA -r host -d /host/path/to/guest/dataset -m /path/to/map etc etc
```

Then just make sure a `grub.cfg` file exists inside the guest dataset containing the right details -

```
timeout=5
menuentry 'guestname (bhyve)' {
    root=hd0,1
    linux ...
    initrd ...
}
```

I've just booted alpine like this and it seemed happy enough. On reboot I was presented with the grub menu and `guestname (bhyve)` option, which then booted by default. Still need to try some other guests and installers.

In this project it probably makes sense to change the existing logic so rather than writing a simple command file, it writes a `grub.cfg` - if it doesn't already exist. Then just change the `grub-bhyve` command line to pick it up. That way existing functionality should be preserved and if the user needs to change the boot commands, they can easily edit the `grub.cfg` file directly.

For fairly random reasons I just ripped all the grub commands out of my code and moved them somewhere the user can edit them. I'm so glad I got stuck in and did it though. The code is much cleaner now and users can basically run whatever commands they like on a per-guest basis, without having to start altering the source code.

**Comment by pr1ntf** [comment]
Sounds about right, I had it working this way in the past. 

This project will have two methods of utilizing `grub-bhyve`: the custom `grub.cfg.` method mentioned above and an "auto" feature similar to what is in use currently, only with no piping to `grub-bhyve`.

More info can be found [here](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0) on the roadmap.

**Comment by pr1ntf** [comment]
There is now a way to use a custom `grub.cfg` file documented [here](https://github.com/pr1ntf/iohyve#use-your-own-custom-grubcfg-and-devicemap-files).

Next on the list is to use "heredocs" to use hardcoded `os` settings for guests listed [here](https://github.com/pr1ntf/iohyve/wiki/Guest-Operating-System-Support).

As always, more info can be found on the [roadmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0).
