### ISSUE TITLE
Unable to boot NetBSD 7

### ISSUE THREAD

**Issue by sevan** [pr1ntf/iohyve#87]
console hangs at the grub-bhyve prompt
`grub> knetbsd -h -r cd0a /netbsd
error: no server is specified.`

**Comment by pr1ntf** [comment]
Can you provide the output of `iohyve getall netbsdguest`?

**Comment by sevan** [comment]
`Getting netbsd7g props...`
`bargs        -A_-H_-P`
`name         netbsd7g`
`install      yes`
`loader       grub-bhyve`
`boot         0`
`con          nmdm1`
`tap          tap1`
`description  Mon_Jan__4_02:06:21_GMT_2016`
`persist      1`
`os           netbsd`
`size         40G`
`cpu          1`
`autogrub     \n`
`ram          256M`

**Comment by pr1ntf** [comment]
This might be another instance of GRUB waiting for input. 

Are you able to run `iohyve console netbsd7g` from another terminal session?

I did get some funky stuff scroll across my screen when I ran `iohyve install nbsd7 nbsd7.iso`, but having `iohyve console nbsd7` in another terminal allowed me to begin the install process.

**Comment by pr1ntf** [comment]
I did some work on GRUB stuff that may have fixed this for you. 

Please update iohyve from git and try again. If you are still seeing problems please let me know and I'll reopen the bug. I'm not able to reproduce on my machine.

**Comment by sevan** [comment]
Apologies, this turned out to be my fault. 
`error: no server is specified` is grub's way of telling you that it can't find something from the device.map or at least In this case, it was the iso file was a different name.
You can confirm what's listed in the map is registered by running `ls` at the grub prompt.
