### ISSUE TITLE
list ordering

### ISSUE THREAD

**Issue by jungle-boogie** [pr1ntf/iohyve#91]
Hello,

Before I submit a pull request, I thought I would check with you...

On your readme and man pages, what's the order things are listed in?
https://raw.githubusercontent.com/pr1ntf/iohyve/master/README.md

I personally prefer alphabetized lists, but maybe you have it organized in most common commands first.

**Comment by pr1ntf** [comment]
The `usage`, `help`, and `man` outputs have no set order right now. The order in which we go through the process of exploring `iohyve` (fetch, install, properties) do have some order to them. 

Thanks for your work!
