### ISSUE TITLE
debian vm stuck at grub> consol

### ISSUE THREAD

**Issue by narkisr** [pr1ntf/iohyve#92]
Following the readme I'm unable to start a debian install:

``` bash
iohyve set debguest loader=grub-bhyve
iohyve set debguest os=debian
iohyve install debguest debian-8.2.0-amd64-i386-netinst.iso
iohyve console debguest
```

Results with:

``` bash
  Minimal BASH-like line editing is supported. For the first word, TAB lists possible command completions. Anywhere else TAB lists
   possible device or file completions.

grub> 
grub>
```

The grub menu is unresponsive

**Comment by pr1ntf** [comment]
I can't reproduce this with my copy of `debian-8.2.0-amd64-i386-netinst.iso` 

If you are still having problems, can you tell me the output of `iohyve getall debguest` and `iohyve version`?

**Comment by narkisr** [comment]
``` bash
Getting debguest props...
size         20G
cpu          1
ram          256M
description  Sun_Jan_10_00:49:19_IST_2016
bargs        -A_-H_-P
boot         0
os           debian
name         debguest
install      yes
autogrub     \n
loader       grub-bhyve
con          nmdm0
persist      1
tap          tap0
```

``` bash
iohyve v0.7 2015/10/27 Im Here for the Party Edition
```

**Comment by pr1ntf** [comment]
Try updating to `0.7.3` either from GitHub or from the latest port snapshot. 

I'm still unable to reproduce with the settings you provided.

**Comment by pr1ntf** [comment]
Also, after updating, run `iohyve destroy debguest` to remove it from VMM before going further.

**Comment by narkisr** [comment]
Ok, iv found the issue 

I didn't use fetch in order to get the iso (iv just downloaded), following the freebsd section I saw that the tool does it magic while setting up the iso 

Thanks

**Comment by pr1ntf** [comment]
Did you use `iohyve cpiso` to copy the ISO to iohyve's ISO storage?

**Comment by narkisr** [comment]
No, I assumed that if I create the folder under /iohyve/ISO it will be ok, once I ran fetch for the BSD guest I notice that the tool create another parent folder (I guess with some ZFS properties) 

The README section that deals with Linux doesn't mention the fetch command this was why I was confused

Thanks

**Comment by pr1ntf** [comment]
Thanks for the info! I should be a bit more clear in the readme on those functions (fetch and cpiso).

**Comment by narkisr** [comment]
Cool, right now I can't seem to get DHCP working on any of the VMs (both Freebsd and Debian) any idea what to look for? (iv set the bridge as instructed in the readme)

(My I suggest that you create a google group? that way I won't pollute the issues history) 
Thanks

**Comment by pr1ntf** [comment]
Feel free to open a separate issue. I don't think the chatter is loud enough here yet to justify a Google Group. This way, everything is in one place for issues and general discourse
