### ISSUE TITLE
Cannot escape iohyve console on some hosts. 

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#95]
If you are having this problem, please tell me about it in this issue thread. 

Please include the host details.

**Comment by JamesLodge** [comment]
FreeBSD 11.0-CURRENT r293055

This is not directly related to iohyve as I create vms by hand, but ~~. and various combinations when ssh'd  (putty) in and running cu result in no action. Input continues to go to the vm console and the escape characters are completely ignored. Only way out is to kill cu process from second terminal or disconnect/connect current session. 

I currently only see this issue on Ubuntu 12.04LTS vms as that is all I'm running right now.

**Comment by pr1ntf** [comment]
After RTFMing on [cu(1)](https://www.freebsd.org/cgi/man.cgi?cu%281%29) you can use `~^D` (Tilde - Ctrl + D) to escape. I find that this works on hosts I have that cannot be escaped by `~~.` (Tilde - Tilde - Period). Going to add this information to the `iohyve` documentation for better clarity.

**Comment by pr1ntf** [comment]
Added more documentation regarding console in the man page. 

Thanks for your help.
